### ISSUE TITLE
Java runtime error

### ISSUE THREAD

**Issue by jtietjens** [toolbox4minecraft/amidst#1011]
Mac OS 11.4
Java v 8 Update 291
Minecraft 1.17
Amidst 4.7
Error message 
	“This version of Minecraft isn’t compatible with your Java installation”
	“MinecraftServer has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0.”

Error messages occurred when selecting “Latest version” or “Latest snapshot” profile in Amidst
I expected to be able to select a world and open map
I was unable to open any world

**Comment by datn** [comment]
Same exact problem: Windows 10, Minecraft 1.17, Amidst 4.7, java 1.8.0_291.

**Comment by JDHnz** [comment]
Read through the comments on #999 and you will find a temporary solution until a new build can be released.

**Comment by zoztruc** [comment]
Hello,
I am having the same trouble with amidst 4.7.
@JDHnz I went to the topic you point here, installed as mentioned at the end of the topic the Java SE Development Kit 16.0.1 for Debian/Linux (I'm using Ubuntu 16.04, still... but it works so nice for me), rebooted and... that didn't help :(
Minecraft 1.17 already came for me with a buggy launcher (had to put libstdc++.so.6 stuff in its folder to make it work) nut it works just fine so I don't think I have any problem with my java or JDK install.
Below the message I get when launching amidst4.7 from command line:

`zoztruc@zoztruc-HP-ZBook-15:~$ java -jar ~/Téléchargements/amidst-v4-7.jar 
[info] Amidst v4.7
[info] Current system time: 2021-06-29 16:54:37.921
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '4.4.0-210-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_292'
[info] System.getProperty("java.vendor") == 'Private Build'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: '/home/zoztruc/.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
New Default Acceleration Threshold: 0
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] There are no updates available.
[info] Successfully loaded remote version list.
[info] using minecraft launcher profile 'Zoz...Yooo de la 1.17 !' with versionId '1.17'
[info] Loading libraries.
[info] Found library com.mojang:blocklist:1.0.5 at file:/home/zoztruc/.minecraft/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar
[info] Found library com.mojang:patchy:2.1.6 at file:/home/zoztruc/.minecraft/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
[info] Found library com.github.oshi:oshi-core:5.7.4 at file:/home/zoztruc/.minecraft/libraries/com/github/oshi/oshi-core/5.7.4/oshi-core-5.7.4.jar
[info] Found library net.java.dev.jna:jna:5.8.0 at file:/home/zoztruc/.minecraft/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
[info] Found library net.java.dev.jna:jna-platform:5.8.0 at file:/home/zoztruc/.minecraft/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar
[info] Found library org.slf4j:slf4j-api:1.8.0-beta4 at file:/home/zoztruc/.minecraft/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
[info] Found library org.apache.logging.log4j:log4j-slf4j18-impl:2.14.1 at file:/home/zoztruc/.minecraft/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar
[info] Found library com.ibm.icu:icu4j:66.1 at file:/home/zoztruc/.minecraft/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
[info] Found library com.mojang:javabridge:1.1.23 at file:/home/zoztruc/.minecraft/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/home/zoztruc/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/home/zoztruc/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/home/zoztruc/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/home/zoztruc/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/home/zoztruc/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/home/zoztruc/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/home/zoztruc/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/home/zoztruc/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.18 at file:/home/zoztruc/.minecraft/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
[info] Found library com.mojang:datafixerupper:4.0.26 at file:/home/zoztruc/.minecraft/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/home/zoztruc/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:2.3.31 at file:/home/zoztruc/.minecraft/libraries/com/mojang/authlib/2.3.31/authlib-2.3.31.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/home/zoztruc/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/home/zoztruc/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/home/zoztruc/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/home/zoztruc/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/home/zoztruc/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.14.1 at file:/home/zoztruc/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.14.1 at file:/home/zoztruc/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/home/zoztruc/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/home/zoztruc/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/home/zoztruc/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[error] amidst.mojangapi.minecraftinterface.MinecraftInterfaceCreationException: This version of Minecraft isn't compatible with your Java installation
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:50)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:26)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:22)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:142)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/server/MinecraftServer has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:290)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:281)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:276)
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:35)
	... 7 more
`

So If any here have another idea, i'm ok to try ^^
thx in advance

zoztruc

**Comment by JDHnz** [comment]
@zoztruc I believe the error you are getting is because it is still using a Java 8 runtime. Perhaps you have more than one version of the JDK installed and available on your path. You might be able to get around this by specifying the full path to the java executable (use the whereis or which commands to find where the Java 16 version of the java executable is installed).

**Comment by zoztruc** [comment]
JDHnz, thank you a lot for your quick answer!
You're right, I have more than one version and I also thought it could explain my problem:

```
zoztruc@zoztruc-HP-ZBook-15:~$ dpkg --list | grep -i jdk | cut -d" " -f3-40
default-jdk                                   2:1.8-56ubuntu2  
default-jdk-headless                          2:1.8-56ubuntu2           
jdk-16.0.1                                    16.0.1-1 
openjdk-8-jdk:amd64                           8u292-b10-0ubuntu1~16.04.1          
openjdk-8-jdk-headless:amd64                  8u292-b10-0ubuntu1~16.04.1                   
openjdk-8-jre:amd64                           8u292-b10-0ubuntu1~16.04.1          
openjdk-8-jre-headless:amd64                  8u292-b10-0ubuntu1~16.04.1

```
jdk-16.0.1 is install, although perhaps not defined as default.
So I figured it could help trying to reconfigure java:

sudo update-alternatives --config java returned me I didn't have another version than the 1.8 (in /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java)... nothing to configure

I thought it could be due to the fact I didn't declare the path to the latest installed version and modified my ~/.profile:

export LD_LIBRARY_PATH=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/amd64/server/:/usr/lib/jvm/jdk-16.0.1

and tried again after updating my profile (. .profile)

... but not better.

just to precise whereis and which doesn't help:

whereis java
java: /usr/bin/java /etc/java /usr/share/java /usr/share/man/man1/java.1.gz

which java
/usr/bin/java

I just installed the JDK... does the jre come with? can the error be their?

thanks again for your help!

zoztruc

**Comment by JDHnz** [comment]
@zoztruc Sorry, it has been decades since I've actively used a unix system, so I'm just going on vague memories here. Yes, the JDK should include the JRE. I did a bit of searching and it looks like you may have to use update-java-alternatives instead of update-alternatives to switch the default between the installed versions (see the accepted answer [here](https://askubuntu.com/questions/740757/switch-between-multiple-java-versions))

**Comment by zoztruc** [comment]
@JDHnz Hello!

finally I got it, thanks to your help :)

I couldn't manage the stuff with update-java-alternatives which refuses to see my new java 16 install, what I didn't understand at first. However trying to install it again but another way with update-alternatives worked:

```
sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-16.0.1/bin/java 1081
sudo update-alternatives --config java

```
Of important note, there is no .jinfo file provided with the Oracle bundle for java installation so I had to point directly on the java executable.
This way I got the java 16 working by default:

```
zoztruc@zoztruc-HP-ZBook-15:~$ java -version
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```
launching amidst4.7 was then ok, and minecraft too :D

So happy so get this tool back, very cool to help navigating in the maps.

Thank you again for your help, and have nice trips in minecraft ;)

**Comment by JDHnz** [comment]
Hey @zoztruc,

Thanks for coming back and letting us know what it was that worked for you! It's always a challenge to help people on platforms different to what you are familiar with, so it is appreciated that you shared your experiences, as that may help someone else with a similar environment to yours.
