### ISSUE TITLE
Bug when attempting to run 1.18.1

### ISSUE THREAD

**Issue by ComputerZombie15** [toolbox4minecraft/amidst#1083]
[info] Amidst v4.6
[info] Current system time: 2021-12-10 21:59:47.108
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_301'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: 'C:\Users\User1\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Successfully loaded remote version list.
[info] using minecraft launcher profile 'Latest version' with versionId '1.18.1'
[info] Loading libraries.
[info] Found library com.mojang:blocklist:1.0.6 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar
[info] Found library com.mojang:patchy:2.1.6 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
[info] Found library com.github.oshi:oshi-core:5.8.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar
[info] Found library net.java.dev.jna:jna:5.9.0 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
[info] Found library net.java.dev.jna:jna-platform:5.9.0 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar
[info] Found library org.slf4j:slf4j-api:1.8.0-beta4 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
[info] Found library org.apache.logging.log4j:log4j-slf4j18-impl:2.14.1 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar
[info] Found library com.ibm.icu:icu4j:69.1 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar
[info] Found library com.mojang:javabridge:1.2.24 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.4 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
[info] Found library io.netty:netty-all:4.1.68.Final at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
[info] Found library com.google.guava:failureaccess:1.0.1 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
[info] Found library com.google.guava:guava:31.0.1-jre at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
[info] Found library org.apache.commons:commons-lang3:3.12.0 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
[info] Found library commons-io:commons-io:2.11.0 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
[info] Found library commons-codec:commons-codec:1.15 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
[info] Found library com.mojang:brigadier:1.0.18 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
[info] Found library com.mojang:datafixerupper:4.0.26 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
[info] Found library com.google.code.gson:gson:2.8.8 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar
[info] Found library com.mojang:authlib:3.2.38 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar
[info] Found library org.apache.commons:commons-compress:1.21 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
[info] Found library org.apache.httpcomponents:httpclient:4.5.13 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
[info] Found library commons-logging:commons-logging:1.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[info] Found library org.apache.httpcomponents:httpcore:4.4.14 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
[info] Found library it.unimi.dsi:fastutil:8.5.6 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.14.1 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.14.1 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/C:/Users/User1/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[crash] Amidst has encounted an uncaught exception on the thread Thread[WorkerExecutor-1,1,main]
[crash] java.lang.UnsupportedClassVersionError: net/minecraft/server/MinecraftServer has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:269)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:260)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:255)
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:33)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:26)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:22)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:142)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by FakenameBill** [comment]
AMIDST has not been updated for 1.18 yet.
But also, you're using an old version. Latest is 4.7, which also won't work with 1.18

**Comment by ComputerZombie15** [comment]
This is what happens when I launch on version 4.6 if I try to use 4.7 it just crashes

**Comment by ComputerZombie15** [comment]
Oh ok thanks

**Comment by Eken-beep** [comment]
When will amidst start working for 1.18?

**Comment by Boobies** [comment]
Never, most likely? The project has been slowly dying over the years.
