### ISSUE TITLE
4234324

### ISSUE THREAD

**Issue by Anonim3123123** [toolbox4minecraft/amidst#1095]
[info] Amidst v4.7
[info] Current system time: 2022-02-06 00:17:43.413
[info] System.getProperty("os.name") == 'Windows 7'
[info] System.getProperty("os.version") == '6.1'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_291'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.getMinecraftDirectory(DotMinecraftDirectoryService.java:81)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.findDotMinecraftDirectory(DotMinecraftDirectoryService.java:73)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createDotMinecraftDirectory(DotMinecraftDirectoryService.java:47)
	at amidst.mojangapi.file.MinecraftInstallation.newLocalMinecraftInstallation(MinecraftInstallation.java:41)
	at amidst.PerApplicationInjector.<init>(PerApplicationInjector.java:67)
	at amidst.Amidst.doStartApplication(Amidst.java:173)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:163)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
[amidst-v4-7.zip](https://github.com/toolbox4minecraft/amidst/files/8008937/amidst-v4-7.zip)

**Comment by Anonim3123123** [comment]
[info] Amidst v4.7
[info] Current system time: 2022-02-06 00:19:42.649
[info] System.getProperty("os.name") == 'Windows 7'
[info] System.getProperty("os.version") == '6.1'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_291'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.getMinecraftDirectory(DotMinecraftDirectoryService.java:81)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.findDotMinecraftDirectory(DotMinecraftDirectoryService.java:73)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createDotMinecraftDirectory(DotMinecraftDirectoryService.java:47)
	at amidst.mojangapi.file.MinecraftInstallation.newLocalMinecraftInstallation(MinecraftInstallation.java:41)
	at amidst.PerApplicationInjector.<init>(PerApplicationInjector.java:67)
	at amidst.Amidst.doStartApplication(Amidst.java:173)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:163)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
