### ISSUE TITLE
Crash when using release 1.1 jar/json and dummy MultiMC directories

### ISSUE THREAD

**Issue by sedrosken** [toolbox4minecraft/amidst#1115]
Per [issue 761](https://github.com/toolbox4minecraft/amidst/issues/761) I've created the requisite dummy directories and launcher_profiles.json under D:\Games\MultiMC so Amidst will recognize it as a valid .minecraft folder. My command line is thus:

> java -jar .\amidst-v4-7.jar -mcjar .\minecraft-1.1-client.jar -mcjson .\1.1.json -mcpath D:\Games\MultiMC

The files are copied to the working directory from the MultiMC\libraries\com\mojang\minecraft\(version) and MultiMC\meta\net.minecraft folders. Trying that command line, either with the jar itself or the distributed executable file, results in the following crash that the program asks me to report here. I suspect that it's not especially useful to you given the fact that custom launcher support is outside the scope of this project.

> [info] Amidst v4.7
[info] Current system time: 2022-12-19 12:43:15.764
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_352'
[info] System.getProperty("java.vendor") == 'Temurin'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: 'D:\Games\MultiMC'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Loading libraries.
[info] Finished loading libraries.
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] amidst.mojangapi.minecraftinterface.MinecraftInterfaceCreationException: Unable to create local minecraft interface
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:48)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:26)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:22)
	at amidst.Application.run(Application.java:57)
	at amidst.Amidst.doStartApplication(Amidst.java:173)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:163)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: error while loading main class; are some libraries missing?
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:295)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:281)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:276)
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:35)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/LWJGLException
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:288)
	... 22 more
Caused by: java.lang.ClassNotFoundException: org.lwjgl.LWJGLException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 26 more

It's perhaps worth noting that this is from running the executable -- running the jar returns a different Java version, one 11.0.12 distributed by Microsoft. From the looks of things this is actually mad at _me_ -- I notice it's complaining about a lack of a LWJGL library, but I'm not sure where I'd put it. On the off-chance this is actually useful to you, I'm posting it here. Feel free to remove it if it's not.

**Comment by lightchao0** [comment]
Having the same issue, running from .bat since I am command line illiterate. 
.bat is as follows
`java -jar E:/Minecraft/Amidst/amidst-v4-7.jar -mcpath E:\Minecraft\MultiMC`
the following error is given as well 
`[error] Error reading launcher_profiles.json
[error] amidst.parsing.FormatException: result was null
        at amidst.parsing.json.JsonReader.read(JsonReader.java:46)
        at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:26)
        at amidst.mojangapi.file.service.DotMinecraftDirectoryService.readLauncherProfilesFrom(DotMinecraftDirectoryService.java:95)
        at amidst.mojangapi.file.MinecraftInstallation.readLauncherProfiles(MinecraftInstallation.java:65)
        at amidst.gui.profileselect.ProfileSelectWindow.scanAndLoadProfiles(ProfileSelectWindow.java:129)
        at amidst.threading.WorkerExecutor.lambda$run$15(WorkerExecutor.java:90)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)`
