### ISSUE TITLE
i tried loading 1.20.1 profile it says this

### ISSUE THREAD

**Issue by apoorvgupt479** [toolbox4minecraft/amidst#1139]
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-macos-arm64
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-windows
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-windows-arm64
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-windows-x86
[info] Found library org.lwjgl:lwjgl:3.3.1 at file:/home/ap/.minecraft/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
[warning] Skipping missing library org.lwjgl:lwjgl:3.3.1:natives-linux
[info] Skipping inactive library org.lwjgl:lwjgl:3.3.1:natives-macos
[info] Skipping inactive library org.lwjgl:lwjgl:3.3.1:natives-macos-arm64
[info] Skipping inactive library org.lwjgl:lwjgl:3.3.1:natives-windows
[info] Skipping inactive library org.lwjgl:lwjgl:3.3.1:natives-windows-arm64
[info] Skipping inactive library org.lwjgl:lwjgl:3.3.1:natives-windows-x86
[info] Found library org.slf4j:slf4j-api:2.0.1 at file:/home/ap/.minecraft/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
[info] Finished loading libraries.
[crash] Amidst has encounted an uncaught exception on the thread Thread[WorkerExecutor-6,1,main]
[crash] java.lang.UnsupportedClassVersionError: net/minecraft/server/MinecraftServer has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:269)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:260)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:255)
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:33)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:26)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:22)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:142)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by FeedTheChunk** [comment]
Amidst is dead.  Hasn't been updated in years.
