### ISSUE TITLE
heelp amidst 4.1 crashed

### ISSUE THREAD

**Issue by engrX11** [toolbox4minecraft/amidst#142]
```
[info] Amidst v4.1
[info] Current system time: 2016-04-01 14:22:43.424
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_73'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\Pelagio Jr\AppData\Roaming\.minecraft', libraries: 'C:\Users\Pelagio Jr\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[warning] cannot find valid version directory for launcher profile 'Forge'
[warning] cannot find valid version directory for launcher profile 'forge'
[info] using minecraft launcher profile 'IvanXavier11' with versionId '1.9-OptiFine_HD_U_B1'
[info] Loading libraries.
[info] Found library: C:\Users\Pelagio Jr\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.9_HD_U_B1\OptiFine-1.9_HD_U_B1.jar
[info] Found library: C:\Users\Pelagio Jr\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.7\launchwrapper-1.7.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-9,1,main]
[crash] java.lang.NoClassDefFoundError: com/google/common/util/concurrent/ListenableFuture
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:135)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:126)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:120)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:34)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:106)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:74)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:82)
	at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.ListenableFuture
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
```

 -i am using MC 1.9 w/ optifine.. pls help me

**Comment by Treer** [comment]
It doesn't work with optifine (see #110), use the MC launcher to create another 1.9 profile and use that one in Amidst.
