### ISSUE TITLE
Amidst is crashing, requesting assistance please

### ISSUE THREAD

**Issue by DizzyDesigner** [toolbox4minecraft/amidst#148]
"Amidst has encountered an uncaught exception on the thread Thread[Thread-4,1,main] Please report this bug on: https://github.com/toolbox4minecraft/amidst/issues/new"  

Here is the error information.  Thank you in advance!

```
[info] Amidst v4.1
[info] Current system time: 2016-04-05 15:33:31.156
[info] System.getProperty("os.name") == 'Windows XP'
[info] System.getProperty("os.version") == '5.1'
[info] System.getProperty("os.arch") == 'x86'
[info] System.getProperty("java.version") == '1.8.0_77'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '32'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Documents and Settings\User\Application Data\.minecraft', libraries: 'C:\Documents and Settings\User\Application Data\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[warning] cannot find valid version directory for launcher profile 'forge'
[warning] cannot find valid version directory for launcher profile 'Jordi's New Twilight Mo Thaum'
[warning] cannot find valid version directory for launcher profile 'Forge Trial'
[warning] cannot find valid version directory for launcher profile 'Furious Forge'
[warning] cannot find valid version directory for launcher profile 'Copy of Dizzy_Designer'
[warning] cannot find valid version directory for launcher profile 'Forge Trial_'
[info] using minecraft launcher profile 'OptiFine' with versionId '1.9.2-OptiFine_HD_U_B1'
[info] Loading libraries.
[info] Found library: C:\Documents and Settings\User\Application Data\.minecraft\libraries\optifine\OptiFine\1.9.2_HD_U_B1\OptiFine-1.9.2_HD_U_B1.jar
[info] Found library: C:\Documents and Settings\User\Application Data\.minecraft\libraries\net\minecraft\launchwrapper\1.7\launchwrapper-1.7.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-4,1,main]
[crash] java.lang.NoClassDefFoundError: com/google/common/util/concurrent/ListenableFuture
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:135)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:126)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:120)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:34)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:106)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:74)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:82)
	at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.ListenableFuture
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
```

**Comment by stefandollase** [comment]
I close this as invalid, because Amidst does not support modded Minecraft. For more information, please read the FAQ: [Can I use Amidst with a modded Minecraft version?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#can-i-use-amidst-with-a-modded-minecraft-version)

Optifine might be supported in a future version, see #110

**Comment by Treer** [comment]
Create a new profile with the Minecraft launcher. Call it something like "Amidst" and select that when Amidst asks you for a profile. Use your normal profile when playing Minecraft (the profile which has Optifine installed).

![minecraft launcher](https://cloud.githubusercontent.com/assets/6390507/14303802/a1b5f534-fbf0-11e5-8d7e-ba1cb15f9126.png)
