### ISSUE TITLE
this keeps poping up everytime i use it

### ISSUE THREAD

**Issue by universalpanda** [toolbox4minecraft/amidst#155]
```
[info] Amidst v4.1
[info] Current system time: 2016-04-15 18:25:43.893
[info] System.getProperty("os.name") == 'Windows 8.1'
[info] System.getProperty("os.version") == '6.3'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_60'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\Owner\AppData\Roaming\.minecraft', libraries: 'C:\Users\Owner\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[warning] cannot find valid version directory for launcher profile 'forge'
[info] using minecraft launcher profile 'UniversalPanda' with versionId '1.9-OptiFine_HD_U_B1'
[info] Loading libraries.
[info] Found library: C:\Users\Owner\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.9_HD_U_B1\OptiFine-1.9_HD_U_B1.jar
[info] Found library: C:\Users\Owner\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.7\launchwrapper-1.7.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-11,1,main]
[crash] java.lang.NoClassDefFoundError: com/google/common/util/concurrent/ListenableFuture
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:135)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:126)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:120)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:34)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:106)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:74)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:82)
	at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.ListenableFuture
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
```

**Comment by Treer** [comment]
Looks like that's an Optifine profile, as a general rule, modded profiles can't be supported.

If you don't already have a non-Optifine profile then create a new profile with the Minecraft launcher. Call it something like "Amidst" and just select that one when Amidst asks you for a profile. Use your normal optifine profile when playing Minecraft.

![minecraft launcher](https://cloud.githubusercontent.com/assets/6390507/14304860/0cd746e8-fbfa-11e5-8451-e5f97cdeeb03.png)


Optifine might be supported one day, see #110

Mod support is also touched on in the FAQ: [Can I use Amidst with a modded Minecraft version?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#can-i-use-amidst-with-a-modded-minecraft-version)
