### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by lecactusjones17** [toolbox4minecraft/amidst#165]
```
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\zackg\AppData\Roaming\.minecraft', libraries: 'C:\Users\zackg\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[warning] cannot find valid version directory for launcher profile '(Default)'
[warning] cannot find valid version directory for launcher profile 'forge'
[info] using minecraft launcher profile 'TBNRCactusJones_' with versionId '1.9.2-OptiFine_HD_U_B1'
[info] Loading libraries.
[info] Found library: C:\Users\zackg\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.9.2_HD_U_B1\OptiFine-1.9.2_HD_U_B1.jar
[info] Found library: C:\Users\zackg\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.7\launchwrapper-1.7.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-7,1,main]
[crash] java.lang.NoClassDefFoundError: com/google/common/util/concurrent/ListenableFuture
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:132)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:124)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:119)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:32)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:84)
	at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.ListenableFuture
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
```

**Comment by Treer** [comment]
As a general rule, modded profiles can't be supported.

If you don't already have a non-Optifine profile then create a new profile with the Minecraft launcher. Call it something like "Amidst" and just select that one when Amidst asks you for a profile. Use your normal optifine profile when playing Minecraft.

![minecraft launcher](https://cloud.githubusercontent.com/assets/6390507/14304860/0cd746e8-fbfa-11e5-8451-e5f97cdeeb03.png)


Optifine might be supported one day, see #110

Mod support is also touched on in the FAQ: [Can I use Amidst with a modded Minecraft version?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#can-i-use-amidst-with-a-modded-minecraft-version)
