### ISSUE TITLE
Amidst Issue - Uncaught Exception on Thread[Thread-6,1,main]

### ISSUE THREAD

**Issue by kgit45** [toolbox4minecraft/amidst#195]
I just opened Amidst for the first time, and attempted to load my Optifine profile.  I was confronted with the following message, which included a request that I report that "Amidst has encountered an uncaught exception on the thread Thread[Thread-6,1,main]"

So I am reporting it to the link that was given in the dialog box.  

The dialog box contained a bunch of code.  I do not know what any of it meant, but here it is:

[info] Amidst v4.1
[info] Current system time: 2016-07-01 15:59:26.56
[info] System.getProperty("os.name") == 'Mac OS X'
[info] System.getProperty("os.version") == '10.11.5'
[info] System.getProperty("os.arch") == 'x86_64'
[info] System.getProperty("java.version") == '1.8.0_91'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Enabling OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: '/Users/Kendall/Library/Application Support/minecraft', libraries: '/Users/Kendall/Library/Application Support/minecraft/libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[info] using minecraft launcher profile 'OptiFine' with versionId '1.10.2-OptiFine_HD_U_C1'
[info] Loading libraries.
[info] Found library: /Users/Kendall/Library/Application Support/minecraft/libraries/optifine/OptiFine/1.10.2_HD_U_C1/OptiFine-1.10.2_HD_U_C1.jar
[info] Found library: /Users/Kendall/Library/Application Support/minecraft/libraries/net/minecraft/launchwrapper/1.7/launchwrapper-1.7.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-6,1,main]
[crash] java.lang.SecurityException: class "aid"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:135)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:126)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:120)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:34)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:106)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:74)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:82)
	at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Hopefully this is sufficient for a bug report; this is all I can think to provide information-wise. 

Best of luck to you.
- K

**Comment by CubeTheThird** [comment]
Amidst does not support modded versions of the game, including Optifine.

**Comment by stefandollase** [comment]
I close this as invalid, because Amidst does not support modded Minecraft.

You can still use Amidst with an unmodded Minecraft profile. To do so, please create a new profile with the Minecraft launcher. Call it something like "Amidst" and use that when Amidst asks you for a profile. Make sure to select the correct Minecraft version when creating the new profile.

![minecraft launcher](https://cloud.githubusercontent.com/assets/6390507/14304860/0cd746e8-fbfa-11e5-8451-e5f97cdeeb03.png)

For more information, please read the FAQ: [Can I use Amidst with a modded Minecraft version?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#can-i-use-amidst-with-a-modded-minecraft-version)

Optifine might be supported in a future version, see #110

**Comment by kgit45** [comment]
Thanks.  Amidst is up and running now with un-modded profile.
