### ISSUE TITLE
Amidst 4.2 beta 2 crash on launch

### ISSUE THREAD

**Issue by Artillect** [toolbox4minecraft/amidst#201]
```
[info] Amidst v4.2-beta2
[info] Current system time: 2016-07-08 20:44:18.114
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_91'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\oreo4\AppData\Roaming\.minecraft', libraries: 'C:\Users\oreo4\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-4,1,main]
[crash] java.lang.NoClassDefFoundError: javax/crypto/BadPaddingException
    at sun.security.rsa.RSASignature.engineVerify(Unknown Source)
    at java.security.Signature$Delegate.engineVerify(Unknown Source)
    at java.security.Signature.verify(Unknown Source)
    at sun.security.pkcs.SignerInfo.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
    at sun.security.util.SignatureFileVerifier.process(Unknown Source)
    at java.util.jar.JarVerifier.processEntry(Unknown Source)
    at java.util.jar.JarVerifier.update(Unknown Source)
    at java.util.jar.JarFile.initializeVerifier(Unknown Source)
    at java.util.jar.JarFile.getInputStream(Unknown Source)
    at sun.misc.URLClassPath$JarLoader$2.getInputStream(Unknown Source)
    at sun.misc.Resource.cachedInputStream(Unknown Source)
    at sun.misc.Resource.getByteBuffer(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.security.jca.ProviderConfig.doLoadProvider(Unknown Source)
    at sun.security.jca.ProviderConfig.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getService(Unknown Source)
    at sun.security.jca.GetInstance.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getDefault(Unknown Source)
    at javax.net.ssl.SSLSocketFactory.getDefault(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at java.net.URL.openConnection(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at amidst.mojangapi.file.URIUtils.newInputStream(URIUtils.java:84)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:43)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:39)
    at amidst.gui.main.UpdateInformationRetriever.retrieve(UpdateInformationRetriever.java:23)
    at amidst.threading.WorkerExecutor.lambda$run$17(WorkerExecutor.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-6,1,main]
[crash] java.lang.NoClassDefFoundError: javax/crypto/BadPaddingException
    at sun.security.rsa.RSASignature.engineVerify(Unknown Source)
    at java.security.Signature$Delegate.engineVerify(Unknown Source)
    at java.security.Signature.verify(Unknown Source)
    at sun.security.pkcs.SignerInfo.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
    at sun.security.util.SignatureFileVerifier.process(Unknown Source)
    at java.util.jar.JarVerifier.processEntry(Unknown Source)
    at java.util.jar.JarVerifier.update(Unknown Source)
    at java.util.jar.JarFile.initializeVerifier(Unknown Source)
    at java.util.jar.JarFile.getInputStream(Unknown Source)
    at sun.misc.URLClassPath$JarLoader$2.getInputStream(Unknown Source)
    at sun.misc.Resource.cachedInputStream(Unknown Source)
    at sun.misc.Resource.getByteBuffer(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.security.jca.ProviderConfig.doLoadProvider(Unknown Source)
    at sun.security.jca.ProviderConfig.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getService(Unknown Source)
    at sun.security.jca.GetInstance.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getDefault(Unknown Source)
    at javax.net.ssl.SSLSocketFactory.getDefault(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at java.net.URL.openConnection(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at amidst.mojangapi.file.URIUtils.newInputStream(URIUtils.java:84)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:43)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:39)
    at amidst.mojangapi.file.json.JsonReader.readRemoteVersionList(JsonReader.java:73)
    at amidst.mojangapi.file.json.JsonReader.readRemoteOrLocalVersionList(JsonReader.java:44)
    at amidst.mojangapi.MojangApi.getVersionList(MojangApi.java:56)
    at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:68)
    at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:56)
    at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:71)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-10,1,main]
[crash] java.lang.NoClassDefFoundError: javax/crypto/BadPaddingException
    at sun.security.rsa.RSASignature.engineVerify(Unknown Source)
    at java.security.Signature$Delegate.engineVerify(Unknown Source)
    at java.security.Signature.verify(Unknown Source)
    at sun.security.pkcs.SignerInfo.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
    at sun.security.util.SignatureFileVerifier.process(Unknown Source)
    at java.util.jar.JarVerifier.processEntry(Unknown Source)
    at java.util.jar.JarVerifier.update(Unknown Source)
    at java.util.jar.JarFile.initializeVerifier(Unknown Source)
    at java.util.jar.JarFile.getInputStream(Unknown Source)
    at sun.misc.URLClassPath$JarLoader$2.getInputStream(Unknown Source)
    at sun.misc.Resource.cachedInputStream(Unknown Source)
    at sun.misc.Resource.getByteBuffer(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.security.jca.ProviderConfig.doLoadProvider(Unknown Source)
    at sun.security.jca.ProviderConfig.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getService(Unknown Source)
    at sun.security.jca.GetInstance.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getDefault(Unknown Source)
    at javax.net.ssl.SSLSocketFactory.getDefault(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at java.net.URL.openConnection(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at amidst.mojangapi.file.URIUtils.newInputStream(URIUtils.java:84)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:43)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:39)
    at amidst.mojangapi.file.json.JsonReader.readRemoteVersionList(JsonReader.java:73)
    at amidst.mojangapi.file.json.JsonReader.readRemoteOrLocalVersionList(JsonReader.java:44)
    at amidst.mojangapi.MojangApi.getVersionList(MojangApi.java:56)
    at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:68)
    at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:56)
    at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:71)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Beginning latest version list load.
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-7,1,main]
[crash] java.lang.NoClassDefFoundError: javax/crypto/BadPaddingException
    at sun.security.rsa.RSASignature.engineVerify(Unknown Source)
    at java.security.Signature$Delegate.engineVerify(Unknown Source)
    at java.security.Signature.verify(Unknown Source)
    at sun.security.pkcs.SignerInfo.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
    at sun.security.util.SignatureFileVerifier.process(Unknown Source)
    at java.util.jar.JarVerifier.processEntry(Unknown Source)
    at java.util.jar.JarVerifier.update(Unknown Source)
    at java.util.jar.JarFile.initializeVerifier(Unknown Source)
    at java.util.jar.JarFile.getInputStream(Unknown Source)
    at sun.misc.URLClassPath$JarLoader$2.getInputStream(Unknown Source)
    at sun.misc.Resource.cachedInputStream(Unknown Source)
    at sun.misc.Resource.getByteBuffer(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.security.jca.ProviderConfig.doLoadProvider(Unknown Source)
    at sun.security.jca.ProviderConfig.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getService(Unknown Source)
    at sun.security.jca.GetInstance.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getDefault(Unknown Source)
    at javax.net.ssl.SSLSocketFactory.getDefault(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at java.net.URL.openConnection(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at amidst.mojangapi.file.URIUtils.newInputStream(URIUtils.java:84)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:43)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:39)
    at amidst.mojangapi.file.json.JsonReader.readRemoteVersionList(JsonReader.java:73)
    at amidst.mojangapi.file.json.JsonReader.readRemoteOrLocalVersionList(JsonReader.java:44)
    at amidst.mojangapi.MojangApi.getVersionList(MojangApi.java:56)
    at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:68)
    at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:56)
    at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:71)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

[info] Attempting to download remote version list...
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-9,1,main]
[crash] java.lang.NoClassDefFoundError: javax/crypto/BadPaddingException
    at sun.security.rsa.RSASignature.engineVerify(Unknown Source)
    at java.security.Signature$Delegate.engineVerify(Unknown Source)
    at java.security.Signature.verify(Unknown Source)
    at sun.security.pkcs.SignerInfo.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
    at sun.security.util.SignatureFileVerifier.process(Unknown Source)
    at java.util.jar.JarVerifier.processEntry(Unknown Source)
    at java.util.jar.JarVerifier.update(Unknown Source)
    at java.util.jar.JarFile.initializeVerifier(Unknown Source)
    at java.util.jar.JarFile.getInputStream(Unknown Source)
    at sun.misc.URLClassPath$JarLoader$2.getInputStream(Unknown Source)
    at sun.misc.Resource.cachedInputStream(Unknown Source)
    at sun.misc.Resource.getByteBuffer(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.security.jca.ProviderConfig.doLoadProvider(Unknown Source)
    at sun.security.jca.ProviderConfig.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getService(Unknown Source)
    at sun.security.jca.GetInstance.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getDefault(Unknown Source)
    at javax.net.ssl.SSLSocketFactory.getDefault(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at java.net.URL.openConnection(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at amidst.mojangapi.file.URIUtils.newInputStream(URIUtils.java:84)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:43)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:39)
    at amidst.mojangapi.file.json.JsonReader.readRemoteVersionList(JsonReader.java:73)
    at amidst.mojangapi.file.json.JsonReader.readRemoteOrLocalVersionList(JsonReader.java:44)
    at amidst.mojangapi.MojangApi.getVersionList(MojangApi.java:56)
    at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:68)
    at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:56)
    at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:71)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-8,1,main]
[crash] java.lang.NoClassDefFoundError: javax/crypto/BadPaddingException
    at sun.security.rsa.RSASignature.engineVerify(Unknown Source)
    at java.security.Signature$Delegate.engineVerify(Unknown Source)
    at java.security.Signature.verify(Unknown Source)
    at sun.security.pkcs.SignerInfo.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.pkcs.PKCS7.verify(Unknown Source)
    at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
    at sun.security.util.SignatureFileVerifier.process(Unknown Source)
    at java.util.jar.JarVerifier.processEntry(Unknown Source)
    at java.util.jar.JarVerifier.update(Unknown Source)
    at java.util.jar.JarFile.initializeVerifier(Unknown Source)
    at java.util.jar.JarFile.getInputStream(Unknown Source)
    at sun.misc.URLClassPath$JarLoader$2.getInputStream(Unknown Source)
    at sun.misc.Resource.cachedInputStream(Unknown Source)
    at sun.misc.Resource.getByteBuffer(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at sun.security.jca.ProviderConfig$2.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.security.jca.ProviderConfig.doLoadProvider(Unknown Source)
    at sun.security.jca.ProviderConfig.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getProvider(Unknown Source)
    at sun.security.jca.ProviderList.getService(Unknown Source)
    at sun.security.jca.GetInstance.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getInstance(Unknown Source)
    at javax.net.ssl.SSLContext.getDefault(Unknown Source)
    at javax.net.ssl.SSLSocketFactory.getDefault(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(Unknown Source)
    at javax.net.ssl.HttpsURLConnection.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
    at java.net.URL.openConnection(Unknown Source)
    at java.net.URL.openStream(Unknown Source)
    at amidst.mojangapi.file.URIUtils.newInputStream(URIUtils.java:84)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:43)
    at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:39)
    at amidst.mojangapi.file.json.JsonReader.readRemoteVersionList(JsonReader.java:73)
    at amidst.mojangapi.file.json.JsonReader.readRemoteOrLocalVersionList(JsonReader.java:44)
    at amidst.mojangapi.MojangApi.getVersionList(MojangApi.java:56)
    at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:68)
    at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:56)
    at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:71)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by stefandollase** [comment]
This seems to be an issue with the `https` connection. Do you still experience the problem or did it occur only once? The error occurred when Amidst tried to read the following two documents. Please check whether you can access both of them.

* https://toolbox4minecraft.github.io/amidst/api/update-information.json
* https://launchermeta.mojang.com/mc/game/version_manifest.json

The first URL should display something like this:

```
{
    "major": 4,
    "minor": 1,
    "message": "",
    "downloadUrl": "https://github.com/toolbox4minecraft/amidst/releases"
}
```

The second should offer you to download a file or display a JSON document that starts with something like this:

```
{"latest":{
```

**Comment by stefandollase** [comment]
Is this still an issue? If it is, please provide the requested information. Otherwise, we are not able to resolve the issue.

**Comment by stefandollase** [comment]
The OP seems to have lost interest in this issue. Thus I close it.
