### ISSUE TITLE
I have an issue with AMIDST while I am using OptiFine 1.10.2 (BUG)

### ISSUE THREAD

**Issue by MatthewStevenGo** [toolbox4minecraft/amidst#204]
Here is the crash report:

[info] Amidst v4.2-beta2
[info] Current system time: 2016-07-12 14:44:14.732
[info] System.getProperty("os.name") == 'Windows 7'
[info] System.getProperty("os.version") == '6.1'
[info] System.getProperty("os.arch") == 'x86'
[info] System.getProperty("java.version") == '1.8.0_91'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '32'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\Claudine\AppData\Roaming\.minecraft', libraries: 'C:\Users\Claudine\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[info] using minecraft launcher profile 'OptiFine' with versionId '1.10.2-OptiFine_HD_U_C1'
[info] Loading libraries.
[info] Found library: C:\Users\Claudine\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.10.2_HD_U_C1\OptiFine-1.10.2_HD_U_C1.jar
[info] Found library: C:\Users\Claudine\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.7\launchwrapper-1.7.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-8,1,main]
[crash] java.lang.NoClassDefFoundError: com/google/common/util/concurrent/ListenableFuture
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:132)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:124)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:119)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:32)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:84)
	at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.ListenableFuture
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more

Can anyone figure it out what happened?

**Comment by CubeTheThird** [comment]
Amidst does not work with modded versions of the game, including Optifine.

**Comment by MatthewStevenGo** [comment]
Ah. I see.

**Comment by MatthewStevenGo** [comment]
Thanks for helping me with that issue. I just thought it works with both modded and unmodded versions of Minecraft.
