### ISSUE TITLE
Found some werid bug for ya

### ISSUE THREAD

**Issue by Watishere11** [toolbox4minecraft/amidst#220]
here's the error:

```
info] Amidst v4.2-beta2
[info] Current system time: 2016-08-03 11:17:52.021
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_101'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\thanhdat\AppData\Roaming\.minecraft', libraries: 'C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[info] using minecraft launcher profile 'OptiFine' with versionId '1.7.2-OptiFine_HD_U_E4'
[info] Loading libraries.
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.7.2_HD_U_E4\OptiFine-1.7.2_HD_U_E4.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.7\launchwrapper-1.7.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\com\mojang\netty\1.6\netty-1.6.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.3.1\vecmath-1.3.1.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\15.0\guava-15.0.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.3\authlib-1.3.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.0\lwjgl-2.9.0.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.0\lwjgl_util-2.9.0.jar
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.0\lwjgl-platform-2.9.0-natives-windows.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20131017
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20131017
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.1-nightly-20131017
[info] Found library: C:\Users\thanhdat\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-6,1,main]
[crash] java.lang.SecurityException: class "ov"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:132)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:124)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:119)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:32)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:84)
	at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by BigAlanM** [comment]
AND AGAIN:  AMIDST DOESN'T WORK WITH OPTIFINE OR ANY OTHER MODDED MINECRAFT JAR FILE

**Comment by ekevoo** [comment]
@BigAlanM Please be civil with other users. The UI provides no hint that Optifine is the culprit and it's unfair to assume that anyone reads the manual. See #205 and [this](http://www.joelonsoftware.com/uibook/chapters/fog0000000062.html).

**Comment by stefandollase** [comment]
I agree with @ekevoo. It is our fault that we don't catch this error. We even ask the user to report the bug when it occurs. Many users including @Watishere11 create their Github account just to be able to report the bug. Thus, we should not be rude to them. The fix is already scheduled for the next release.

That being said ...

---

I close this as invalid, because Amidst does not support modded Minecraft.

You can still use Amidst with an unmodded Minecraft profile. To do so, please create a new profile with the Minecraft launcher. Call it something like "Amidst" and use that when Amidst asks you for a profile. Make sure to select the correct Minecraft version when creating the new profile.

![minecraft launcher](https://cloud.githubusercontent.com/assets/6390507/14304860/0cd746e8-fbfa-11e5-8451-e5f97cdeeb03.png)

For more information, please read the FAQ: [Can I use Amidst with a modded Minecraft version?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#can-i-use-amidst-with-a-modded-minecraft-version)

Optifine might be supported in a future version, see #110

**Comment by Watishere11** [comment]
No, it isn't optifine and modded... nvm i'm just gonna reinstall my
minecraft :/

2016-08-04 3:13 GMT+07:00 Stefan Dollase <notifications@github.com>:

**Comment by stefandollase** [comment]
@Watishere11

```
[info] using minecraft launcher profile 'OptiFine' with versionId '1.7.2-OptiFine_HD_U_E4'
```

This line, taken from your bug report, clearly indicates that you were using an OptiFine profile. If there is an issue with unmodded profiles, please post another bug report.
