### ISSUE TITLE
Crashed.

### ISSUE THREAD

**Issue by AugiteSoul** [toolbox4minecraft/amidst#222]
```
[info] Searching for biome color profiles.
[info] Unable to find biome color profile folder.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.8-forge1.8-11.14.4.1577 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.8-forge1.8-11.14.4.1577\1.8-forge1.8-11.14.4.1577.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10\1.7.10-Forge10.13.4.1614-1.7.10.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.8-forge1.8-11.14.4.1577 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.8-forge1.8-11.14.4.1577\1.8-forge1.8-11.14.4.1577.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10\1.7.10-Forge10.13.4.1614-1.7.10.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10\1.7.10-Forge10.13.4.1614-1.7.10.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10\1.7.10-Forge10.13.4.1614-1.7.10.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10\1.7.10-Forge10.13.4.1614-1.7.10.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10\1.7.10-Forge10.13.4.1614-1.7.10.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10\1.7.10-Forge10.13.4.1614-1.7.10.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1492-1.7.10 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1492-1.7.10\1.7.10-Forge10.13.4.1492-1.7.10.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10\1.7.10-Forge10.13.4.1614-1.7.10.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.8.9-forge1.8.9-11.15.1.1875 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.8.9-forge1.8.9-11.15.1.1875\1.8.9-forge1.8.9-11.15.1.1875.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.8.9-forge1.8.9-11.15.1.1875 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.8.9-forge1.8.9-11.15.1.1875\1.8.9-forge1.8.9-11.15.1.1875.jar is missing or a directory.
[warning] Unable to load MinecraftVersion at path: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10 because jarFile: C:\Users\Arthur S\AppData\Roaming\.minecraft\versions\1.7.10-Forge10.13.4.1614-1.7.10\1.7.10-Forge10.13.4.1614-1.7.10.jar is missing or a directory.
[info] Successfully loaded version list. URL: https://s3.amazonaws.com/Minecraft.Download/versions/versions.json
[info] Reading minecraft.jar...
[info] Jar load complete.
[info] Searching for classes...
[debug] Found: [ByteClass aii] as WorldType | CCStringMatch
[debug] Found: [ByteClass ayo] as GenLayer | CCLongMatch
[debug] Found: [ByteClass aym] as IntCache | CCStringMatch
[debug] Found: [ByteClass caf$1] as WorldType | CCRequire
[debug] Found: [ByteClass caf$1] as GenLayer | CCRequire
[debug] Found: [ByteClass caf$1] as IntCache | CCRequire
[info] Class search complete.
[info] Generating version ID...
[info] Loading libraries.
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\mojang\netty\1.6\netty-1.6.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.22\authlib-1.5.22.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.9.3\realms-1.9.3.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.0.12_mojang\fastutil-7.0.12_mojang.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar
[info] Loading libraries.
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\mojang\netty\1.6\netty-1.6.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.22\authlib-1.5.22.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.9.3\realms-1.9.3.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.0.12_mojang\fastutil-7.0.12_mojang.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[info] Found library: C:\Users\Arthur S\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar
[info] Identified Minecraft [unknown] with versionID of rboqmdkcpd[Lls;mp[J[[Jml
[info] Loading classes...
[warning] java.lang.NoSuchMethodException: ayo.a(long, aii) Unable to find class method (GenLayer / ayo) (initializeAllBiomeGenerators / a)
[info] Classes loaded.
[info] Minecraft load complete.
[debug] Attempting to create world with seed: 117, type: default, and the following generator options:
[debug] 
[crash] Amidst has encounted an uncaught exception on thread: Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
	at amidst.minecraft.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:49)
	at amidst.minecraft.MinecraftUtil.createWorld(MinecraftUtil.java:62)
	at MoF.Project.<init>(Project.java:109)
	at MoF.Project.<init>(Project.java:57)
	at MoF.Project.<init>(Project.java:51)
	at amidst.gui.menu.AmidstMenu$FileMenu$SeedMenuItem$1.actionPerformed(AmidstMenu.java:190)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by stefandollase** [comment]
This bug report if generated by an old version of Amidst. Please download the latest version of Amidst from https://github.com/toolbox4minecraft/amidst/releases However, as i can see in #221, you already did that. I posted an answer there, explaining that modded Minecraft is not supported by Amidst.
