### ISSUE TITLE
[crash] java.lang.NoClassDefFoundError: io/netty/buffer/ByteBufOutputStream

### ISSUE THREAD

**Issue by MTM123** [toolbox4minecraft/amidst#226]
`[info] Amidst v4.2-beta2
[info] Current system time: 2016-09-05 22:31:09.827
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'x86'
[info] System.getProperty("java.version") == '1.8.0_91'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '32'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\MTM\AppData\Roaming\.minecraft', libraries: 'C:\Users\MTM\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[warning] cannot find valid version directory for launcher profile 'forge'
[info] using minecraft launcher profile 'OptiFine' with versionId '1.8.9-OptiFine_HD_U_H6'
[info] Loading libraries.
[info] Found library: C:\Users\MTM\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.8.9_HD_U_H6\OptiFine-1.8.9_HD_U_H6.jar
[info] Found library: C:\Users\MTM\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.7\launchwrapper-1.7.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-7,1,main]
[crash] java.lang.NoClassDefFoundError: io/netty/buffer/ByteBufOutputStream
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:132)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:124)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:119)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:32)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:84)
	at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: io.netty.buffer.ByteBufOutputStream
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more

`

Crashed when trying to use Optifine profile

**Comment by BigAlanM** [comment]
You tried to run Amidst with an Optifine profile.
Amidst ONLY works with plain ummodded vanilla MInecraft.jar profiles.

**Comment by MTM123** [comment]
Thanks for info!
