### ISSUE TITLE
I just flat out can't run AMIDST... 

### ISSUE THREAD

**Issue by cleverruse** [toolbox4minecraft/amidst#303]
I get this error for both the jar and the exe for 4.2, Any advice in resolving this would be appriciated. 

> [crash] Amidst has encounted an uncaught exception on the thread Thread[main,5,main]
[crash] java.lang.IllegalArgumentException: java.io.IOException: Stream closed
	at amidst.ResourceLoader.getProperties(ResourceLoader.java:50)
	at amidst.Amidst.createMetadata(Amidst.java:61)
	at amidst.Amidst.parseCommandLineArgumentsAndRun(Amidst.java:44)
	at amidst.Amidst.main(Amidst.java:30)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.util.Properties$LineReader.readLine(Unknown Source)
	at java.util.Properties.load0(Unknown Source)
	at java.util.Properties.load(Unknown Source)
	at amidst.ResourceLoader.getProperties(ResourceLoader.java:45)
	... 3 more

>

**Comment by stefandollase** [comment]
Can you post the complete crash report, please?

**Comment by stefandollase** [comment]
The OP seems to have lost interest in this issue. Thus I close it.
