### ISSUE TITLE
Admist crash

### ISSUE THREAD

**Issue by EnderGaming360** [toolbox4minecraft/amidst#311]
```
[info] Amidst v4.2
[info] Current system time: 2017-03-10 15:09:09.188
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_121'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\Daniel\AppData\Roaming\.minecraft', libraries: 'C:\Users\Daniel\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] There are no updates available.
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile ''
	at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:80)
	at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:59)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[info] using minecraft launcher profile 'EnderGaming360' with versionId '1.8.9 - 5zig Mod'
[info] Loading libraries.
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\eu\the5zig\The5zigMod\1.8.9_3.9.20\The5zigMod-1.8.9_3.9.20.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\eu\the5zig\Mods\1.8.9_3.9.20\Mods-1.8.9_3.9.20.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.7\launchwrapper-1.7.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\com\mojang\netty\1.6\netty-1.6.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.7.59\realms-1.7.59.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch-platform\6.5\twitch-platform-6.5-natives-windows-32.jar
[info] Found library: C:\Users\Daniel\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-32.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-9,1,main]
[crash] java.lang.SecurityException: class "nt"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:142)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:134)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:129)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:33)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:100)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by stefandollase** [comment]
This looks like you are trying to use a modded profile. Amidst does not support modded Minecraft. Please use an unmodded Minecraft Profile with the same version. See also [Using Amidst](https://github.com/toolbox4minecraft/amidst/wiki/Using-Amidst).
