### ISSUE TITLE
Amidst crashed!

### ISSUE THREAD

**Issue by TheGuke** [toolbox4minecraft/amidst#330]
```
[crash] Amidst has encounted an uncaught exception on the thread Thread[main,5,main]
[crash] java.lang.IllegalArgumentException: javax.imageio.IIOException: Can't create cache file!
	at amidst.ResourceLoader.getImage(ResourceLoader.java:38)
	at amidst.Amidst.createMetadata(Amidst.java:62)
	at amidst.Amidst.parseCommandLineArgumentsAndRun(Amidst.java:44)
	at amidst.Amidst.main(Amidst.java:30)
Caused by: javax.imageio.IIOException: Can't create cache file!
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:361)
	at javax.imageio.ImageIO.read(ImageIO.java:1397)
	at amidst.ResourceLoader.getImage(ResourceLoader.java:34)
	... 3 more
Caused by: java.nio.file.FileSystemException: /var/folders/d7/fdb3cm_s7bxd_fnlj1vqtdxw0000gn/T/imageio5940654223757223703.tmp: No space left on device
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:897)
	at javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:102)
	at com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(InputStreamImageInputStreamSpi.java:69)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
	... 5 more
```

**Comment by stefandollase** [comment]
```
Caused by: java.nio.file.FileSystemException: /var/folders/d7/fdb3cm_s7bxd_fnlj1vqtdxw0000gn/T/imageio5940654223757223703.tmp: No space left on device
```
This is the relevant line: No space left on device.
