### ISSUE TITLE
Amidst said that I need to report this

### ISSUE THREAD

**Issue by ZeroGamer03** [toolbox4minecraft/amidst#335]
So, this is the crash report:

```
[info] Amidst v4.2
[info] Current system time: 2017-06-21 18:33:01.033
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_131'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\Eemil\AppData\Roaming\.minecraft', libraries: 'C:\Users\Eemil\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] There are no updates available.
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile ''
	at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:80)
	at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:59)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'PvP-modit'
	at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:80)
	at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:59)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'OptiFine'
	at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:80)
	at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:59)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'forge'
	at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:80)
	at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:59)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[info] using minecraft launcher profile '1.12' with versionId 'OnePointTwelve'
[info] Loading libraries.
[info] Found library: C:\Users\Eemil\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.12_HD_U_C2\OptiFine-1.12_HD_U_C2.jar
[info] Found library: C:\Users\Eemil\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-7,1,main]
[crash] java.lang.NoClassDefFoundError: io/netty/buffer/ByteBufOutputStream
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:142)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:134)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:129)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:33)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:100)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: io.netty.buffer.ByteBufOutputStream
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
```

**Comment by stefandollase** [comment]
Thanks for the report. Amidst v4.2 does not support Minecraft 1.12. Please download the most recent version [here](https://github.com/toolbox4minecraft/amidst/releases).
