### ISSUE TITLE
Thread[AWT-EventQueue-0,6,main] Uncaught Exception

### ISSUE THREAD

**Issue by NamrednE125** [toolbox4minecraft/amidst#351]
[info] Amidst v4.3-beta2
[info] Current system time: 2017-10-15 08:24:30.547
[info] System.getProperty("os.name") == 'Windows 7'
[info] System.getProperty("os.version") == '6.1'
[info] System.getProperty("os.arch") == 'x86'
[info] System.getProperty("java.version") == '1.8.0_144'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '32'
[info] Not using OpenGL.
[info] Biome profile activated: default
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
	at java.io.File.<init>(Unknown Source)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.getMinecraftDirectory(DotMinecraftDirectoryService.java:80)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.findDotMinecraftDirectory(DotMinecraftDirectoryService.java:72)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createDotMinecraftDirectory(DotMinecraftDirectoryService.java:45)
	at amidst.mojangapi.file.MinecraftInstallation.newLocalMinecraftInstallation(MinecraftInstallation.java:41)
	at amidst.PerApplicationInjector.<init>(PerApplicationInjector.java:66)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$91(Amidst.java:162)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Produced the error by Launch Amidst

Expected the program to open
Received a error pop-up

**Comment by stefandollase** [comment]
It seems like `System.getenv("APPDATA")` returns `null` on your system. Maybe someone with a Windows machine can further investigate this issue?
