### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Medamyy168** [toolbox4minecraft/amidst#354]
```
[info] Amidst v4.3-beta2
[info] Current system time: 2017-11-26 23:45:13.728
[info] System.getProperty("os.name") == 'Windows 7'
[info] System.getProperty("os.version") == '6.1'
[info] System.getProperty("os.arch") == 'x86'
[info] System.getProperty("java.version") == '1.8.0_151'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '32'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\DELL\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] There are no updates available.
[info] Successfully loaded remote version list.
[info] Successfully loaded profile list.
[info] using minecraft launcher profile 'OptiFine' with versionId '1.12-OptiFine_HD_U_C5'
[info] Loading libraries.
[info] Found library optifine:OptiFine:1.12_HD_U_C5 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/optifine/OptiFine/1.12_HD_U_C5/OptiFine-1.12_HD_U_C5.jar
[info] Found library net.minecraft:launchwrapper:1.12 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
[info] Found library optifine:OptiFine:1.12_HD_U_C5 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/optifine/OptiFine/1.12_HD_U_C5/OptiFine-1.12_HD_U_C5.jar
[info] Found library net.minecraft:launchwrapper:1.12 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
[info] Found library com.mojang:patchy:1.1 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library com.paulscode:codecjorbis:20101023 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library com.paulscode:codecwav:20101023 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library com.paulscode:libraryjavasound:20101123 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library com.paulscode:librarylwjglopenal:20100824 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
[info] Found library com.paulscode:soundsystem:20120107 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library io.netty:netty-all:4.1.9.Final at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[warning] Skipping missing library com.mojang:authlib:1.5.25
[info] Found library com.mojang:realms:1.10.17 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:7.1.0 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Found library org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
[info] Found library org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
[info] Found library org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[info] Found library net.java.jinput:jinput-platform:2.0.5 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/C:/Users/DELL/AppData/Roaming/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-4,1,main]
[crash] java.lang.SecurityException: class "rj"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:152)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:144)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:139)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:31)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.create(LocalMinecraftInterface.java:20)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:26)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:17)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:102)
	at amidst.threading.WorkerExecutor.lambda$run$31(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by stefandollase** [comment]
It seems like you wanted to use an OptiFine Profile. Amidst does not support OptiFine. Please try to use an ordinary profile instead.
