### ISSUE TITLE
Amidst will not start

### ISSUE THREAD

**Issue by bigfoot547** [toolbox4minecraft/amidst#357]
Amidst crashes upon execution:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: amidst/Amidst : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

P.S. I tried all amidst releases on this repository and I use Debian 8 with java 8 (or thereabouts)
@stefandollase help please :)

**Comment by bigfoot547** [comment]
Never mind, I updated my java. Turns out I only have java 7...
