### ISSUE TITLE
Crash when load a profile

### ISSUE THREAD

**Issue by iLeowis** [toolbox4minecraft/amidst#367]
This is the error

[info] Amidst v4.3-beta2
[info] Current system time: 2018-01-22 16:25:03.316
[info] System.getProperty("os.name") == 'Windows 8'
[info] System.getProperty("os.version") == '6.2'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_151'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\iLeoU_000\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] using minecraft launcher profile 'Vanilla' with versionId '1.11.2'
[info] Loading libraries.
[warning] Skipping missing library com.mojang:netty:1.6
[info] Found library oshi-project:oshi-core:1.1 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[warning] Skipping missing library net.java.dev.jna:jna:3.4.0
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[warning] Skipping missing library net.sf.jopt-simple:jopt-simple:4.6
[info] Found library com.paulscode:codecjorbis:20101023 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library com.paulscode:codecwav:20101023 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library com.paulscode:libraryjavasound:20101123 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library com.paulscode:librarylwjglopenal:20100824 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
[info] Found library com.paulscode:soundsystem:20120107 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[warning] Skipping missing library io.netty:netty-all:4.0.23.Final
[warning] Skipping missing library com.google.guava:guava:17.0
[warning] Skipping missing library org.apache.commons:commons-lang3:3.3.2
[warning] Skipping missing library commons-io:commons-io:2.4
[warning] Skipping missing library commons-codec:commons-codec:1.9
[info] Found library net.java.jinput:jinput:2.0.5 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[warning] Skipping missing library com.google.code.gson:gson:2.2.4
[warning] Skipping missing library com.mojang:authlib:1.5.24
[warning] Skipping missing library com.mojang:realms:1.10.16
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[warning] Skipping missing library it.unimi.dsi:fastutil:7.0.12_mojang
[warning] Skipping missing library org.apache.logging.log4j:log4j-api:2.0-beta9
[warning] Skipping missing library org.apache.logging.log4j:log4j-core:2.0-beta9
[info] Found library org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
[info] Found library org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
[info] Found library org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[info] Skipping inactive library org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[info] Found library net.java.jinput:jinput-platform:2.0.5 at file:/C:/Users/iLeoU_000/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
[info] Finished loading libraries.
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-10,1,main]
[crash] java.lang.NoClassDefFoundError: com/google/common/util/concurrent/ListenableFuture
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:152)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:144)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:139)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:31)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.create(LocalMinecraftInterface.java:20)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:26)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:17)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:102)
	at amidst.threading.WorkerExecutor.lambda$run$31(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.ListenableFuture
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more

**Comment by cleverruse** [comment]
Is your version of Windows 8 64bit? You may need 32bit.. Or you may need to
reinstall Java all together, to insure it's not conflicting with an older
version.
