### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by Linkdc12** [toolbox4minecraft/amidst#397]
[info] Amidst v4.1
[info] Current system time: 2018-05-14 00:07:24.896
[info] System.getProperty("os.name") == 'Windows 8.1'
[info] System.getProperty("os.version") == '6.3'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_171'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\alumno\AppData\Roaming\.minecraft', libraries: 'C:\Users\alumno\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[info] using minecraft launcher profile 'linkdc' with versionId '1.9.4-OptiFine_HD_U_D8'
[info] Loading libraries.
[info] Found library: C:\Users\alumno\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.9.4_HD_U_D8\OptiFine-1.9.4_HD_U_D8.jar
[info] Found library: C:\Users\alumno\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.7\launchwrapper-1.7.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-6,1,main]
[crash] java.lang.NoClassDefFoundError: io/netty/buffer/ByteBufOutputStream
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:135)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:126)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:120)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:34)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:106)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:74)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:82)
	at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: io.netty.buffer.ByteBufOutputStream
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more

**Comment by Linkdc12** [comment]
in 1.9.4

**Comment by moulins** [comment]
I see a `[info] using minecraft launcher profile 'linkdc' with versionId '1.9.4-OptiFine_HD_U_D8'` mentioned in the logs.  
Amidst only support vanilla profiles, and even Optifine will likely break something (it *may* work on other versions, but if it does, it is pure coincidence). Please use a vanilla 1.9.4 profile, it should work correctly.
