### ISSUE TITLE
amidst crashed

### ISSUE THREAD

**Issue by DJUDE9903** [toolbox4minecraft/amidst#401]
```
[info] Amidst v4.2
[info] Current system time: 2018-06-23 15:04:28.659
[info] System.getProperty("os.name") == 'Mac OS X'
[info] System.getProperty("os.version") == '10.13.4'
[info] System.getProperty("os.arch") == 'x86_64'
[info] System.getProperty("java.version") == '1.8.0_121'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Enabling OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: '/Users/523813/Library/Application Support/minecraft', libraries: '/Users/523813/Library/Application Support/minecraft/libraries'
[info] using biome profiles at: 'biome'
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-5,1,main]
[crash] java.lang.ExceptionInInitializerError
	at javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:65)
	at javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2587)
	at javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2611)
	at sun.security.ssl.CipherSuite$BulkCipher.isUnlimited(CipherSuite.java:535)
	at sun.security.ssl.CipherSuite$BulkCipher.<init>(CipherSuite.java:507)
	at sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:614)
	at sun.security.ssl.SSLContextImpl.getApplicableCipherSuiteList(SSLContextImpl.java:293)
	at sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:41)
	at sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:424)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.security.Provider$Service.getImplClass(Provider.java:1634)
	at java.security.Provider$Service.newInstance(Provider.java:1592)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:979)
	at java.net.URL.openStream(URL.java:1045)
	at amidst.mojangapi.file.URIUtils.newInputStream(URIUtils.java:84)
	at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:43)
	at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:39)
	at amidst.gui.main.UpdateInformationRetriever.retrieve(UpdateInformationRetriever.java:23)
	at amidst.threading.WorkerExecutor.lambda$run$19(WorkerExecutor.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:88)
	... 33 more
Caused by: java.lang.SecurityException: Cannot locate policy or framework files!
	at javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:255)
	at javax.crypto.JceSecurity.access$000(JceSecurity.java:48)
	at javax.crypto.JceSecurity$1.run(JceSecurity.java:80)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:77)
	... 33 more

[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Beginning latest version list load.
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-7,1,main]
[crash] java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.security.Provider$Service.getImplClass(Provider.java:1634)
	at java.security.Provider$Service.newInstance(Provider.java:1592)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:979)
	at java.net.URL.openStream(URL.java:1045)
	at amidst.mojangapi.file.URIUtils.newInputStream(URIUtils.java:84)
	at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:43)
	at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:39)
	at amidst.mojangapi.file.json.JsonReader.readRemoteVersionList(JsonReader.java:78)
	at amidst.mojangapi.file.json.JsonReader.readRemoteOrLocalVersionList(JsonReader.java:49)
	at amidst.mojangapi.MojangApi.getVersionList(MojangApi.java:56)
	at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:68)
	at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:59)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[info] Attempting to download remote version list...
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-9,1,main]
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-6,1,main]
[crash] java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.security.Provider$Service.getImplClass(Provider.java:1634)
	at java.security.Provider$Service.newInstance(Provider.java:1592)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:979)
	at java.net.URL.openStream(URL.java:1045)
	at amidst.mojangapi.file.URIUtils.newInputStream(URIUtils.java:84)
	at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:43)
	at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:39)
	at amidst.mojangapi.file.json.JsonReader.readRemoteVersionList(JsonReader.java:78)
	at amidst.mojangapi.file.json.JsonReader.readRemoteOrLocalVersionList(JsonReader.java:49)
	at amidst.mojangapi.MojangApi.getVersionList(MojangApi.java:56)
	at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:68)
	at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:59)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[crash] java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.security.Provider$Service.getImplClass(Provider.java:1634)
	at java.security.Provider$Service.newInstance(Provider.java:1592)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:979)
	at java.net.URL.openStream(URL.java:1045)
	at amidst.mojangapi.file.URIUtils.newInputStream(URIUtils.java:84)
	at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:43)
	at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:39)
	at amidst.mojangapi.file.json.JsonReader.readRemoteVersionList(JsonReader.java:78)
	at amidst.mojangapi.file.json.JsonReader.readRemoteOrLocalVersionList(JsonReader.java:49)
	at amidst.mojangapi.MojangApi.getVersionList(MojangApi.java:56)
	at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:68)
	at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:59)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-8,1,main]
[crash] java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.security.Provider$Service.getImplClass(Provider.java:1634)
	at java.security.Provider$Service.newInstance(Provider.java:1592)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:979)
	at java.net.URL.openStream(URL.java:1045)
	at amidst.mojangapi.file.URIUtils.newInputStream(URIUtils.java:84)
	at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:43)
	at amidst.mojangapi.file.URIUtils.newReader(URIUtils.java:39)
	at amidst.mojangapi.file.json.JsonReader.readRemoteVersionList(JsonReader.java:78)
	at amidst.mojangapi.file.json.JsonReader.readRemoteOrLocalVersionList(JsonReader.java:49)
	at amidst.mojangapi.MojangApi.getVersionList(MojangApi.java:56)
	at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:68)
	at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:59)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by moulins** [comment]
This looks like a Java misconfiguration. What were you doing when the crash occured?

**Comment by moulins** [comment]
Optifine modifies the Minecraft JAR, so trying to open an Optifine profile will confuse Amidst, and you'll get a crash. Use a separate vanilla profile instead.
