### ISSUE TITLE
Could not load 1.13-pre5/6

### ISSUE THREAD

**Issue by k-jiang** [toolbox4minecraft/amidst#405]
Yesterday it was fine, but today when I run Amidst it doesn't want to load 1.13-pre5/6 for some unknown reasons. Exception `unable to create local minecraft interface` is thrown in a dialog. I can play 1.13-pre5/6 with no problem though, using Linux launcher v1.6.89-j.
```
[info] Amidst v4.3-beta3
[info] Current system time: 2018-07-06 11:32:17.414
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '4.13.0-43-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_171'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: '/home/kenneth/.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
New Default Acceleration Threshold: 0
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile '1.12.2-forge'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:146)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[info] There are no updates available.
[info] Successfully loaded remote version list.
[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile '1.12.2-forge'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:146)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[info] using minecraft launcher profile '1.13-pre6' with versionId '1.13-pre6'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/home/kenneth/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/home/kenneth/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/home/kenneth/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/home/kenneth/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/home/kenneth/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/home/kenneth/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library com.paulscode:codecjorbis:20101023 at file:/home/kenneth/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library com.paulscode:codecwav:20101023 at file:/home/kenneth/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library com.paulscode:libraryjavasound:20101123 at file:/home/kenneth/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library com.paulscode:soundsystem:20120107 at file:/home/kenneth/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/home/kenneth/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/home/kenneth/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/home/kenneth/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/home/kenneth/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/home/kenneth/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/home/kenneth/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/home/kenneth/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:0.1.27 at file:/home/kenneth/.minecraft/libraries/com/mojang/brigadier/0.1.27/brigadier-0.1.27.jar
[info] Found library com.mojang:datafixerupper:1.0.12 at file:/home/kenneth/.minecraft/libraries/com/mojang/datafixerupper/1.0.12/datafixerupper-1.0.12.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/home/kenneth/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.5.25 at file:/home/kenneth/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/home/kenneth/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/home/kenneth/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/home/kenneth/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/home/kenneth/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:7.1.0 at file:/home/kenneth/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/home/kenneth/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/home/kenneth/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/home/kenneth/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/home/kenneth/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/home/kenneth/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Unable to recognise Minecraft Version with the magic string "adexntxoj[Lsz;vl[J[[Jvhuturbvautwxpopscbtplpm".
[info] Reading 1.13-pre6.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class OverworldGenSettings: bnv
[error] amidst.mojangapi.minecraftinterface.MinecraftInterfaceCreationException: unable to create local minecraft interface
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:44)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:25)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:17)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:102)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: cannot find a real class matching the symbolic class Bootstrap
	at amidst.clazz.symbolic.declaration.SymbolicClassDeclaration.handleNoMatch(SymbolicClassDeclaration.java:64)
	at amidst.clazz.translator.ClassTranslator.addResult(ClassTranslator.java:56)
	at amidst.clazz.translator.ClassTranslator.translate(ClassTranslator.java:43)
	at amidst.clazz.Classes.createSymbolicClassMap(Classes.java:39)
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:34)
	... 7 more
```

**Comment by k-jiang** [comment]
Sorry I was running a wrong version of Amidst. closing it.
P.S. another issue is 1.13-forge is shown as "not found", it is an old bug I know but it seems that Amidst doesn't handle this type of json well.
