### ISSUE TITLE
Something broke + log

### ISSUE THREAD

**Issue by kylerchin** [toolbox4minecraft/amidst#412]
[info] Amidst v4.2
[info] Current system time: 2018-07-22 12:13:49.404
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '4.15.0-23-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '10.0.2'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: '/root/.minecraft', libraries: '/root/.minecraft/libraries'
[info] using minecraft version directory. versionId: 'unknown', jar file: '/root/.minecraft/versions/1.12/1.12.jar', json file: '/root/.minecraft/versions/1.12/1.12.json'
[info] Loading libraries.
[info] Found library: /root/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library: /root/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library: /root/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library: /root/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library: /root/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library: /root/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library: /root/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library: /root/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library: /root/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library: /root/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
[info] Found library: /root/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library: /root/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
[info] Found library: /root/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library: /root/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library: /root/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library: /root/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library: /root/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library: /root/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library: /root/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library: /root/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library: /root/.minecraft/libraries/com/mojang/realms/1.10.17/realms-1.10.17.jar
[info] Found library: /root/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library: /root/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library: /root/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library: /root/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library: /root/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
[info] Found library: /root/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library: /root/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Found library: /root/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
[info] Found library: /root/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
[info] Found library: /root/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
[info] Skipping library: org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
[info] Skipping library: org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
[info] Found library: /root/.minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
[info] Found library: /root/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar
[info] Found library: /root/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar
[info] Skipping library: ca.weblite:java-objc-bridge:1.0.0
[info] Skipping library: ca.weblite:java-objc-bridge:1.0.0
[info] Unable to recognise Minecraft Version with the magic string "ujrjoxmsrw[Lom;pj[J[[Jpf".
[info] Reading 1.12.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceCreationException: unable to create local minecraft interface
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:50)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.mojangapi.MojangApiBuilder.construct(MojangApiBuilder.java:41)
	at amidst.Application.createMojangApi(Application.java:54)
	at amidst.Application.<init>(Application.java:42)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$60(Amidst.java:162)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: amidst.clazz.real.JarFileParsingException: Error extracting jar data.
	at amidst.clazz.real.RealClasses.readRealClassesFromJarFile(RealClasses.java:37)
	at amidst.clazz.real.RealClasses.fromJarFile(RealClasses.java:23)
	at amidst.clazz.Classes.createSymbolicClassMap(Classes.java:35)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:35)
	... 21 more
Caused by: amidst.clazz.real.RealClassCreationException: unable to create real class for the class: cif
	at amidst.clazz.real.RealClassBuilder.construct(RealClassBuilder.java:18)
	at amidst.clazz.real.RealClasses.readRealClass(RealClasses.java:72)
	at amidst.clazz.real.RealClasses.readJarFileEntry(RealClasses.java:58)
	at amidst.clazz.real.RealClasses.readJarFile(RealClasses.java:45)
	at amidst.clazz.real.RealClasses.readRealClassesFromJarFile(RealClasses.java:33)
	... 24 more
Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
	at amidst.clazz.real.RealClassBuilder.skipAttributes(RealClassBuilder.java:265)
	at amidst.clazz.real.RealClassBuilder.readFields(RealClassBuilder.java:227)
	at amidst.clazz.real.RealClassBuilder.doConstruct(RealClassBuilder.java:47)
	at amidst.clazz.real.RealClassBuilder.construct(RealClassBuilder.java:16)
	... 28 more

**Comment by moulins** [comment]
You are using an old version of Amidst; please use the latest version (4.3-beta3, you can find it [here](https://github.com/toolbox4minecraft/amidst/releases)) and look if the crash happens again.

**Comment by dickbalaska** [comment]
And running as root is a really really bad idea.

**Comment by kylerchin** [comment]
@dickbalaska How is root access a bad idea?

**Comment by dickbalaska** [comment]
https://www.google.com/search?q=why+you+should+not+run+as+root

**Comment by moulins** [comment]
No response in 6 months; closing this issue.
