### ISSUE TITLE
NullPointerException while loading Minecraft profile, caused by compatibility problem in amidst fork amidstest

### ISSUE THREAD

**Issue by juozaspo** [toolbox4minecraft/amidst#428]
After running amidstest (amidst for minetest, https://github.com/Treer/amidstest) then running amidst again, it crash while loading Minecraft profile. This issue is caused by Treer/amidstest#22, where amidstest config files are written to `biome` and `/home/yourusername/.java/.userPrefs/amidst` directories (on Linux). After renaming/deleting those directories amidst works ok again.

Amidst should detect invalid biome profile data instead of crashing what it does now.

```
[info] Amidst v4.3-beta4
[info] Current system time: 2018-08-15 10:54:04.036
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '4.15.0-30-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_181'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: '/home/juozas/.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Successfully loaded remote version list.
[info] There are no updates available.
[info] using minecraft launcher profile 'Latest version' with versionId '1.13'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/home/juozas/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/home/juozas/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/home/juozas/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/home/juozas/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/home/juozas/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/home/juozas/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library com.paulscode:codecjorbis:20101023 at file:/home/juozas/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library com.paulscode:codecwav:20101023 at file:/home/juozas/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library com.paulscode:libraryjavasound:20101123 at file:/home/juozas/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library com.paulscode:soundsystem:20120107 at file:/home/juozas/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/home/juozas/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/home/juozas/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/home/juozas/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/home/juozas/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/home/juozas/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/home/juozas/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/home/juozas/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:0.1.27 at file:/home/juozas/.minecraft/libraries/com/mojang/brigadier/0.1.27/brigadier-0.1.27.jar
[info] Found library com.mojang:datafixerupper:1.0.16 at file:/home/juozas/.minecraft/libraries/com/mojang/datafixerupper/1.0.16/datafixerupper-1.0.16.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/home/juozas/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.5.25 at file:/home/juozas/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/home/juozas/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/home/juozas/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/home/juozas/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/home/juozas/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:7.1.0 at file:/home/juozas/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/home/juozas/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/home/juozas/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6-natives-linux.jar
[info] Found library com.mojang:realms:1.13.3 at file:/home/juozas/.minecraft/libraries/com/mojang/realms/1.13.3/realms-1.13.3.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/home/juozas/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6-natives-linux.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/home/juozas/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/home/juozas/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Recognised Minecraft Version 1.13 with the magic string "adrxquaom[Ltc;vo[J[[Jvkuwuubvavhxaprpvccipopp".
[info] Reading 1.13.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class WorldType: axz
[info] Found class LayerUtil: bzp
[info] Found class GenLayer: bzo
[info] Found class Bootstrap: pf
[info] Found class OverworldGenSettings: bol
[info] Found class Biome: ayn
[info] Class search complete.
[info] Loading classes...
[info] Classes loaded.
[info] Minecraft load complete.
[info] Checking for additional biome profiles.
[info] Found biome profile directory.
[info] Found default biome profile.
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
	at amidst.settings.biomeprofile.BiomeProfile.validate(BiomeProfile.java:59)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.createFromFile(BiomeProfileDirectory.java:94)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:72)
	at amidst.settings.biomeprofile.BiomeProfileDirectory.visitProfiles(BiomeProfileDirectory.java:65)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.initParentMenu(BiomeProfileMenuFactory.java:136)
	at amidst.gui.main.menu.BiomeProfileMenuFactory.<init>(BiomeProfileMenuFactory.java:129)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings_BiomeProfile(AmidstMenuBuilder.java:142)
	at amidst.gui.main.menu.AmidstMenuBuilder.create_Settings(AmidstMenuBuilder.java:117)
	at amidst.gui.main.menu.AmidstMenuBuilder.createMenuBar(AmidstMenuBuilder.java:50)
	at amidst.gui.main.menu.AmidstMenuBuilder.<init>(AmidstMenuBuilder.java:32)
	at amidst.gui.main.PerMainWindowInjector.<init>(PerMainWindowInjector.java:99)
	at amidst.PerApplicationInjector.createMainWindow(PerApplicationInjector.java:101)
	at amidst.Application.displayMainWindow(Application.java:73)
	at amidst.gui.profileselect.LocalProfileComponent.loadFinished(LocalProfileComponent.java:116)
	at amidst.threading.WorkerExecutor.lambda$null$8(WorkerExecutor.java:72)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```

**Comment by juozaspo** [comment]
Minetest biome files (generated by running amidstest-v1-2-beta.jar, for minetest) attached.
[biome.tar.gz](https://github.com/toolbox4minecraft/amidst/files/2290035/biome.tar.gz)
