### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by yakbait** [toolbox4minecraft/amidst#431]
[info] Amidst v4.3-beta4
[info] Current system time: 2018-08-21 19:32:24.626
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '4.15.0-32-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '10.0.2'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[crash] Amidst has encounted an uncaught exception on the thread Thread[main,5,main]
[crash] java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1494)
	at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1312)
	at java.desktop/javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1421)
	at amidst.Amidst.startApplication(Amidst.java:162)
	at amidst.Amidst.run(Amidst.java:82)
	at amidst.Amidst.parseCommandLineArgumentsAndRun(Amidst.java:50)
	at amidst.Amidst.main(Amidst.java:30)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 18 more

**Comment by moulins** [comment]
This looks a lot like [this issue](https://www.minecraftforum.net/forums/support/java-edition-support/2823654-linux-client-wont-run).

Make sure you are using the `openjdk-8-jre` package and see if the bug still happens.

**Comment by Treer** [comment]
I've tried hard coded an error message for this over in a fork (https://github.com/Treer/amidstest/commit/a4dfd27b2f4df83999d7cd6efd46474a18336910), after someone with this problem [confirmed one of the the linked solutions worked for them](https://github.com/Treer/amidstest/issues/23).

**Comment by moulins** [comment]
@Treer: Having an error message seems a good idea, could you make a PR with your changes?

**Comment by Moosfet** [comment]
I had what seems to be the same problem, but merely "sudo apt-get install openjdk-8-jre" wasn't enough.  I had to follow that up with "sudo update-alternatives --config java" and selecting Java 8 to be the default.  

FWIW this is coming from a fresh install of Linux Mint 19, which comes with this broken Java 10 by default.  I couldn't even get it to launch Minecraft until I downloaded a new launcher.  Now that I've downgraded to Java 8 the old launcher works fine again.

**Comment by moulins** [comment]
Isn't there a `openjdk-10-jre` package you could use? I know there `openjdk-9-jre` exists, and Amidst run fine with it.

**Comment by Moosfet** [comment]
It looks like my choices are 8 and 11:

# apt-cache search openjdk jre
default-jre - Standard Java or Java compatible Runtime
default-jre-headless - Standard Java or Java compatible Runtime (headless)
openjdk-11-jre - OpenJDK Java runtime, using Hotspot JIT
openjdk-11-jre-headless - OpenJDK Java runtime, using Hotspot JIT (headless)
libhsdis0-fcml - HotSpot disassembler plugin using FCML
libreoffice - office productivity suite (metapackage)
openjdk-11-jre-zero - Alternative JVM for OpenJDK, using Zero
openjdk-8-jre - OpenJDK Java runtime, using Hotspot JIT
openjdk-8-jre-dcevm - Alternative VM for OpenJDK 8 with enhanced class redefinition
openjdk-8-jre-headless - OpenJDK Java runtime, using Hotspot JIT (headless)
openjdk-8-jre-zero - Alternative JVM for OpenJDK, using Zero/Shark
java-package - Utility for creating Java Debian packages

My Minecraft server also seems to run better on the old Java 8.

**Comment by moulins** [comment]
No response in 6 months; closing this issue.
