### ISSUE TITLE
1.14 Snapshot aren't supported

### ISSUE THREAD

**Issue by breon** [toolbox4minecraft/amidst#460]
There have been a couple of weeks of snapshots for 1.14, which include new biomes. Has anyone looked at the current build to see if it will work with the new snapshots?

Cheers,
Breon

**Comment by moulins** [comment]
Amidst doesn't actually work for the new 1.14 snapshots, and will instantly crash.

I've been waiting for the new MCP mappings to investigate the issue.

**Comment by NatoBoram** [comment]
I tried to load 1.14 and got the following errors.

```java
java -jar amidst-v4-3-beta5.jar 
[info] Amidst v4.3-beta5
[info] Current system time: 2018-11-13 19:54:23.561
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '4.18.0-10-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '11.0.1'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: '/home/nato/.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
New Default Acceleration Threshold: 0
[info] Scanning for profiles.
[info] There are no updates available.
[info] Successfully loaded remote version list.
[info] Successfully loaded profile list.
[info] using minecraft launcher profile 'Latest snapshot' with versionId '18w45a'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/home/nato/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/home/nato/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/home/nato/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/home/nato/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/home/nato/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/home/nato/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library com.paulscode:codecjorbis:20101023 at file:/home/nato/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library com.paulscode:codecwav:20101023 at file:/home/nato/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library com.paulscode:libraryjavasound:20101123 at file:/home/nato/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library com.paulscode:soundsystem:20120107 at file:/home/nato/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/home/nato/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/home/nato/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/home/nato/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/home/nato/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/home/nato/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/home/nato/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/home/nato/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.14 at file:/home/nato/.minecraft/libraries/com/mojang/brigadier/1.0.14/brigadier-1.0.14.jar
[info] Found library com.mojang:datafixerupper:1.0.21 at file:/home/nato/.minecraft/libraries/com/mojang/datafixerupper/1.0.21/datafixerupper-1.0.21.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/home/nato/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.5.25 at file:/home/nato/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/home/nato/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/home/nato/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/home/nato/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/home/nato/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/home/nato/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/home/nato/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/home/nato/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Found library com.mojang:realms:1.14.0 at file:/home/nato/.minecraft/libraries/com/mojang/realms/1.14.0/realms-1.14.0.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/home/nato/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/home/nato/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/home/nato/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Unable to recognise Minecraft Version with the magic string "afbadwuspgwg[Jwcvovmcaaxhxtqlqqcfqqiqjya".
[info] Reading 18w45a.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class Bootstrap: pz
[info] Found class Biome: bav
[info] Found class WorldType: baf
[info] Found class RegistryKey: pw
[error] amidst.mojangapi.minecraftinterface.MinecraftInterfaceCreationException: unable to create local minecraft interface
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:44)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:25)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:17)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:102)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: cannot find a real class matching the symbolic class OverworldGenSettings
	at amidst.clazz.symbolic.declaration.SymbolicClassDeclaration.handleNoMatch(SymbolicClassDeclaration.java:64)
	at amidst.clazz.translator.ClassTranslator.addResult(ClassTranslator.java:56)
	at amidst.clazz.translator.ClassTranslator.translate(ClassTranslator.java:43)
	at amidst.clazz.Classes.createSymbolicClassMap(Classes.java:39)
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:34)
	... 7 more
```

**Comment by moulins** [comment]
Yes, something changed in the Minecraft code for the 1.14 snapshots, and I'm waiting for the MCP mappings to investigate the issue.

**Comment by NatoBoram** [comment]
Oh, sorry! I misread your response the first time.

It seems like a lot of projects are waiting for those mappings. Good luck!

**Comment by darthvader45** [comment]
Yeah, cannot wait for 1.14 snapshot support.  Gonna be finding illager towers, new villages, etc.

**Comment by moulins** [comment]
Since commit 15953d62, 1.14 snapshots (until `19w09a`) are working !  
1.14 features have also been added (Bambou Jungles, Pillagers Outposts and new biomes for villages).

I'll close this issue for now.

**Comment by darthvader45** [comment]
Thanks, I've been looking for 1.14 village seeds with a plains village
that's not too broken up by the terrain.  Makes it much easier to defend
against those darned pillager attacks.

**Comment by dojofemy** [comment]
moulins, how do I download your fix and set it up so it works? I have the amidst-v4-3-beta5 and I just added all the files from the fix you uploaded to the same folder, so application and files are together.. and when I launch it with snapshot 19w07a it crashes.

**Comment by moulins** [comment]
> how do I download your fix and set it up so it works?

Until a new Amidst version is released (probably when 1.14 has come out), you'll have to build from the source code yourself. See [here](https://github.com/toolbox4minecraft/amidst/wiki/Setting-up-the-Environment) and [here](https://github.com/toolbox4minecraft/amidst/wiki/Building-from-Source-Code) for instructions (warning: it's pretty technical!).

**Comment by darthvader45** [comment]
Alrighty, I'm really close, yet it says no compiler.  I'll make sure to have a jdk installed so it should work.

**Comment by darthvader45** [comment]
Alrighty, I managed to compile a jar, though no way to package said jar as an exe.  I'll wait for the official release for that.  Unless someone knows a way to package it.

**Comment by darthvader45** [comment]
Alrighty, I managed to compile a jar, though no way to package said jar as an exe.  I'll wait for the official release for that.  Unless someone knows a way to package it.

**Comment by maystorm** [comment]
> Alrighty, I managed to compile a jar, though no way to package said jar as an exe. I'll wait for the official release for that. Unless someone knows a way to package it.

Just try to run it from the command line ("DOS prompt") with:

java -jar <filename>.jar

It works just fine here on Linux, however, should be the same syntax on Windows.
