### ISSUE TITLE
v4.3-beta5: Blank GUI, no errors

### ISSUE THREAD

**Issue by CatastropheBlack** [toolbox4minecraft/amidst#462]
Amidst v4.3-beta5 opens an almost blank window with no obvious GUI elements after selecting a profile to load. No errors shown in terminal, as if program is running correctly.

Profile selection window:
![screenshot at 2018-11-08 11-49-00](https://user-images.githubusercontent.com/33291018/48220642-1b037b00-e34d-11e8-93fd-98b25cac3e08.png)

Main program window:
![screenshot at 2018-11-08 11-49-45](https://user-images.githubusercontent.com/33291018/48220647-1dfe6b80-e34d-11e8-89a5-afdcf0191aeb.png)

Terminal output: 
`[info] Amidst v4.3-beta5
[info] Current system time: 2018-11-08 11:48:55.946
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '4.10.0-38-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_181'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: '/home/<USER>/.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
New Default Acceleration Threshold: 0
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'Latest version'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:146)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'Latest snapshot'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:146)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[info] Successfully loaded remote version list.
[info] There are no updates available.
[info] using minecraft launcher profile '1.13.2' with versionId '1.13.2'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/home/<USER>/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/home/<USER>/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/home/<USER>/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/home/<USER>/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/home/<USER>/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/home/<USER>/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library com.paulscode:codecjorbis:20101023 at file:/home/<USER>/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library com.paulscode:codecwav:20101023 at file:/home/<USER>/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library com.paulscode:libraryjavasound:20101123 at file:/home/<USER>/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library com.paulscode:soundsystem:20120107 at file:/home/<USER>/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/home/<USER>/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/home/<USER>/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/home/<USER>/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/home/<USER>/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/home/<USER>/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/home/<USER>/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/home/<USER>/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.14 at file:/home/<USER>/.minecraft/libraries/com/mojang/brigadier/1.0.14/brigadier-1.0.14.jar
[info] Found library com.mojang:datafixerupper:1.0.19 at file:/home/<USER>/.minecraft/libraries/com/mojang/datafixerupper/1.0.19/datafixerupper-1.0.19.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/home/<USER>/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.5.25 at file:/home/<USER>/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/home/<USER>/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/home/<USER>/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/home/<USER>/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/home/<USER>/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/home/<USER>/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/home/<USER>/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/home/<USER>/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Found library com.mojang:realms:1.13.9 at file:/home/<USER>/.minecraft/libraries/com/mojang/realms/1.13.9/realms-1.13.9.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/home/<USER>/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/home/<USER>/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Unable to recognise Minecraft Version with the magic string "aduxrubomvp[Jvluxuvbvavlxbprpvcctpopp".
[info] Reading 1.13.2.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class Biome: ayu
[info] Found class Bootstrap: pf
[info] Found class RegistryKey: pc
[info] Found class Registry: fc
[info] Found class LayerUtil: bzy
[info] Found class GenLayer: bzx
[info] Found class WorldType: ayg
[info] Found class OverworldGenSettings: bou
[info] Class search complete.
[info] Loading classes...
[info] Classes loaded.
[info] Minecraft load complete.

`

**Comment by pajicadvance** [comment]
Amidst doesn't support 1.13.2 yet, only up to 1.13.1

**Comment by CatastropheBlack** [comment]
Tried using 1.13.1, same issue:

```
[info] Amidst v4.3-beta5
[info] Current system time: 2018-11-13 20:47:27.388
[info] System.getProperty("os.name") == 'Linux'
[info] System.getProperty("os.version") == '4.10.0-38-generic'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_181'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: '/home/<USER>/.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
New Default Acceleration Threshold: 0
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'Latest snapshot'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:146)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'Latest version'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:146)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[info] Successfully loaded remote version list.
[info] There are no updates available.
[info] using minecraft launcher profile '1.13.1' with versionId '1.13.1'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/home/<USER>/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/home/<USER>/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/home/<USER>/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/home/<USER>/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/home/<USER>/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/home/<USER>/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library com.paulscode:codecjorbis:20101023 at file:/home/<USER>/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
[info] Found library com.paulscode:codecwav:20101023 at file:/home/<USER>/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
[info] Found library com.paulscode:libraryjavasound:20101123 at file:/home/<USER>/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
[info] Found library com.paulscode:soundsystem:20120107 at file:/home/<USER>/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/home/<USER>/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/home/<USER>/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/home/<USER>/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/home/<USER>/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/home/<USER>/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/home/<USER>/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/home/<USER>/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.14 at file:/home/<USER>/.minecraft/libraries/com/mojang/brigadier/1.0.14/brigadier-1.0.14.jar
[info] Found library com.mojang:datafixerupper:1.0.16 at file:/home/<USER>/.minecraft/libraries/com/mojang/datafixerupper/1.0.16/datafixerupper-1.0.16.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/home/<USER>/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.5.25 at file:/home/<USER>/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/home/<USER>/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/home/<USER>/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/home/<USER>/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/home/<USER>/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/home/<USER>/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/home/<USER>/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/home/<USER>/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Found library com.mojang:realms:1.13.8 at file:/home/<USER>/.minecraft/libraries/com/mojang/realms/1.13.8/realms-1.13.8.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
[info] Found library org.lwjgl:lwjgl:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl/3.1.6/lwjgl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-jemalloc:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.1.6/lwjgl-jemalloc-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-openal:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.1.6/lwjgl-openal-3.1.6-natives-linux.jar
[info] Found library org.lwjgl:lwjgl-opengl:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.1.6/lwjgl-opengl-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-glfw:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.1.6/lwjgl-glfw-3.1.6.jar
[info] Found library org.lwjgl:lwjgl-stb:3.1.6 at file:/home/<USER>/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.1.6/lwjgl-stb-3.1.6.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/home/<USER>/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
[info] Found library com.mojang:text2speech:1.10.3 at file:/home/<USER>/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Skipping inactive library ca.weblite:java-objc-bridge:1.0.0
[info] Finished loading libraries.
[info] Recognised Minecraft Version 1.13.1 with the magic string "aduxrubomvp[Jvluxuvbvavkxbprpvccspopp".
[info] Reading 1.13.1.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class Bootstrap: pf
[info] Found class GenLayer: bzw
[info] Found class RegistryKey: pc
[info] Found class Registry: fc
[info] Found class Biome: ayt
[info] Found class OverworldGenSettings: bot
[info] Found class WorldType: ayf
[info] Found class LayerUtil: bzx
[info] Class search complete.
[info] Loading classes...
[info] Classes loaded.
[info] Minecraft load complete.


```

**Comment by JaHolliman** [comment]
I have the same issue, however I also edited amidst to work with 1.13.2.
The GUI not appearing was getting frustrating, but I noticed that maximizing the window brought back full functionality, with the menu bar appear at the top thereafter.
I hope this works for you! I am running Arch.

**Comment by Wychmire** [comment]
Having this issue as well on v4.3. Can't load 1.14.3 or 1.13. The output of `java -version` is `openjdk version "1.8.0_202"`
 Full log is [here](https://privatebin.net/?aadb3ce14a00b006#FD2AWQvn3MouUZnMYc2AWBYkE9z7qWRYrQ7CMSFbsbgQ). Maximizing the window doesn't work
