### ISSUE TITLE
Amidst crash on Rift profile load

### ISSUE THREAD

**Issue by free-muffin** [toolbox4minecraft/amidst#473]
c/v of dump

[info] Amidst v4.2
[info] Current system time: 2019-02-17 14:32:08.587
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'x86'
[info] System.getProperty("java.version") == '1.8.0_201'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '32'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\fmmv0\AppData\Roaming\.minecraft', libraries: 'C:\Users\fmmv0\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] There are no updates available.
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[info] using minecraft launcher profile 'Rift' with versionId '1.13.2-rift-1.0.4-106'
[info] Loading libraries.
[info] Found library: C:\Users\fmmv0\AppData\Roaming\.minecraft\libraries\com\github\Chocohead\Rift\jitpack-SNAPSHOT\Rift-jitpack-SNAPSHOT.jar
[info] Found library: C:\Users\fmmv0\AppData\Roaming\.minecraft\libraries\org\dimdev\mixin\0.7.11-SNAPSHOT\mixin-0.7.11-SNAPSHOT.jar
[info] Found library: C:\Users\fmmv0\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm\6.2\asm-6.2.jar
[info] Found library: C:\Users\fmmv0\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-commons\6.2\asm-commons-6.2.jar
[info] Found library: C:\Users\fmmv0\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-tree\6.2\asm-tree-6.2.jar
[info] Found library: C:\Users\fmmv0\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-8,1,main]
[crash] java.lang.NoClassDefFoundError: com/mojang/brigadier/Message
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:142)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:134)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:129)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:33)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:100)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.mojang.brigadier.Message
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more

**Comment by moulins** [comment]
Amidst doesn't support modded profiles; use a vanilla profile instead.
