### ISSUE TITLE
Crash 1.14 

### ISSUE THREAD

**Issue by mtado** [toolbox4minecraft/amidst#484]
[info] Amidst v4.2
[info] Current system time: 2019-05-05 19:10:21.237
[info] System.getProperty("os.name") == 'Mac OS X'
[info] System.getProperty("os.version") == '10.14.4'
[info] System.getProperty("os.arch") == 'x86_64'
[info] System.getProperty("java.version") == '1.8.0_201'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Enabling OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: '/Users/muhammedtlb/Library/Application Support/minecraft', libraries: '/Users/muhammedtlb/Library/Application Support/minecraft/libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] There are no updates available.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'forge'
	at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:80)
	at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:59)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[info] using minecraft launcher profile '' with versionId 'fabric-loader-0.4.6+build.141-1.14+build.7'
[info] Loading libraries.
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/net/fabricmc/tiny-mappings-parser/0.1.1.8/tiny-mappings-parser-0.1.1.8.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/net/fabricmc/sponge-mixin/0.7.11.30/sponge-mixin-0.7.11.30.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/net/fabricmc/tiny-remapper/0.1.0.33/tiny-remapper-0.1.0.33.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/org/ow2/asm/asm/7.1/asm-7.1.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/org/ow2/asm/asm-analysis/7.1/asm-analysis-7.1.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/org/ow2/asm/asm-tree/7.1/asm-tree-7.1.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/org/ow2/asm/asm-util/7.1/asm-util-7.1.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/net/fabricmc/yarn/1.14+build.7/yarn-1.14+build.7.jar
[info] Found library: /Users/muhammedtlb/Library/Application Support/minecraft/libraries/net/fabricmc/fabric-loader/0.4.6+build.141/fabric-loader-0.4.6+build.141.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-7,1,main]
[crash] java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:142)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:134)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:129)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:33)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:100)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

**Comment by moulins** [comment]
1.14 support is included in the main branch of Amidst, and will be in the next release ;).
