### ISSUE TITLE
Cannot build 1.13.2 world

### ISSUE THREAD

**Issue by SlimeDog** [toolbox4minecraft/amidst#487]
AMIDST 4.3-beta6
Java 1.8.0_202-b08
MacOS Mojave 10.14.4

Profile: 1.13.2
Seed: -5322040752997563589

```
[info] Creating world with seed '-5322040752997563589' and type 'Default'
[info] Using the following generator options: 
[warning] amidst.mojangapi.minecraftinterface.MinecraftInterfaceException: unable to create world
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:228)
	at amidst.mojangapi.minecraftinterface.LoggingMinecraftInterface.createWorld(LoggingMinecraftInterface.java:26)
	at amidst.mojangapi.world.WorldBuilder.create(WorldBuilder.java:115)
	at amidst.mojangapi.world.WorldBuilder.from(WorldBuilder.java:65)
	at amidst.mojangapi.RunningLauncherProfile.createWorld(RunningLauncherProfile.java:69)
	at amidst.gui.main.WorldSwitcher.displayWorld(WorldSwitcher.java:67)
	at amidst.gui.main.Actions.newFromSeed(Actions.java:77)
	at amidst.gui.main.Actions.newFromSeed(Actions.java:64)
	at amidst.gui.main.menu.Menus.lambda$item$2(Menus.java:133)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at amidst.clazz.symbolic.SymbolicConstructor.newInstance(SymbolicConstructor.java:37)
	at amidst.clazz.symbolic.SymbolicConstructor.call(SymbolicConstructor.java:25)
	at amidst.clazz.symbolic.SymbolicClass.callConstructor(SymbolicClass.java:79)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.getGenSettings(LocalMinecraftInterface.java:267)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:216)
	... 47 more
Caused by: java.lang.ExceptionInInitializerError
	at bol.<init>(SourceFile:24)
	at bou.<init>(SourceFile:3)
	... 56 more
Caused by: java.lang.RuntimeException: Accessed Blocks before Bootstrap!
	at bct.<clinit>(SourceFile:13)
	... 58 more

```

**Comment by BigAlanM** [comment]
I'm having the same problem. 4.3 beta 6 seems to work with all versions back to 1.6.4 and probably earlier but will not work with 1.13.2 in any way. Ctrl-R, Ctrl-N, or File> Open save game...
I does, however, work with 1.14.2.
