### ISSUE TITLE
Test failing since commit 93534d1

### ISSUE THREAD

**Issue by Scrumplex** [toolbox4minecraft/amidst#490]
When building against the latest commit 93534d1 the tests fail.
Build log:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------------< amidst:amidst >----------------------------
[INFO] Building amidst 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ amidst ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install-file (install-jnbt) @ amidst ---
[INFO] pom.xml not found in JNBT_1.3.jar
[INFO] Installing /run/media/scrumplex/DATA/.cache/yay/amidst-git/src/amidst-git/lib/JNBT_1.3.jar to /home/scrumplex/.m2/repository/jnbt/jnbt/1.3/jnbt-1.3.jar
[INFO] Installing /tmp/mvninstall11746049586504912312.pom to /home/scrumplex/.m2/repository/jnbt/jnbt/1.3/jnbt-1.3.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.458 s
[INFO] Finished at: 2019-05-15T16:41:34+02:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------------< amidst:amidst >----------------------------
[INFO] Building amidst 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- properties-maven-plugin:1.0.0:read-project-properties (default) @ amidst ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ amidst ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 56 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ amidst ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 314 source files to /run/media/scrumplex/DATA/.cache/yay/amidst-git/src/amidst-git/target/classes
[WARNING] /run/media/scrumplex/DATA/.cache/yay/amidst-git/src/amidst-git/src/main/java/amidst/gui/main/menu/MenuShortcuts.java: /run/media/scrumplex/DATA/.cache/yay/amidst-git/src/amidst-git/src/main/java/amidst/gui/main/menu/MenuShortcuts.java uses or overrides a deprecated API.
[WARNING] /run/media/scrumplex/DATA/.cache/yay/amidst-git/src/amidst-git/src/main/java/amidst/gui/main/menu/MenuShortcuts.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ amidst ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 141 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ amidst ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 45 source files to /run/media/scrumplex/DATA/.cache/yay/amidst-git/src/amidst-git/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ amidst ---
[INFO] Surefire report directory: /run/media/scrumplex/DATA/.cache/yay/amidst-git/src/amidst-git/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running amidst.mojangapi.world.test.RecognisedVersionTest
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.041 sec <<< FAILURE!
shouldPreventDifferencesInIdentifierAndName(amidst.mojangapi.world.test.RecognisedVersionTest)  Time elapsed: 0.004 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<_1_14_1[]> but was:<_1_14_1[_]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at amidst.mojangapi.world.test.RecognisedVersionTest.shouldPreventDifferencesInIdentifierAndName(RecognisedVersionTest.java:25)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running amidst.mojangapi.world.test.TestWorldEntryEquality
[info] Unable to find spawn biome. Falling back to [0, 0].
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.693 sec
Running amidst.mojangapi.world.test.CoordinateUtilsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running amidst.logging.MessageFormatterTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec

Results :

Failed tests:   shouldPreventDifferencesInIdentifierAndName(amidst.mojangapi.world.test.RecognisedVersionTest): expected:<_1_14_1[]> but was:<_1_14_1[_]>

Tests run: 16, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.613 s
[INFO] Finished at: 2019-05-15T16:41:43+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project amidst: There are test failures.
[ERROR] 
[ERROR] Please refer to /run/media/scrumplex/DATA/.cache/yay/amidst-git/src/amidst-git/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by moulins** [comment]
Thanks for bringing this to my attention!
