### ISSUE TITLE
Amidst Crashed!

### ISSUE THREAD

**Issue by masonha** [toolbox4minecraft/amidst#495]
[info] Amidst v4.2
[info] Current system time: 2019-05-22 14:11:01.609
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'x86'
[info] System.getProperty("java.version") == '1.8.0_101'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '32'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\mason\AppData\Roaming\.minecraft', libraries: 'C:\Users\mason\AppData\Roaming\.minecraft\libraries'
[info] using biome profiles at: 'biome'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://launchermeta.mojang.com/mc/game/version_manifest.json
[info] There are no updates available.
[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'forge'
	at amidst.mojangapi.file.json.launcherprofiles.LauncherProfileJson.createValidVersionDirectory(LauncherProfileJson.java:80)
	at amidst.gui.profileselect.LocalProfileComponent.tryFind(LocalProfileComponent.java:59)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[info] using minecraft launcher profile 'aris' with versionId '1.14-Aristois'
[info] Loading libraries.
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\net\fabricmc\sponge-mixin\0.7.11.27\sponge-mixin-0.7.11.27.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\net\fabricmc\tiny-mappings-parser\0.1.1.8\tiny-mappings-parser-0.1.1.8.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\net\fabricmc\tiny-remapper\0.1.0.33\tiny-remapper-0.1.0.33.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader-sat4j\2.3.5.4\fabric-loader-sat4j-2.3.5.4.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\com\google\jimfs\jimfs\1.1\jimfs-1.1.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm\7.0\asm-7.0.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-analysis\7.0\asm-analysis-7.0.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-commons\7.0\asm-commons-7.0.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-tree\7.0\asm-tree-7.0.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-util\7.0\asm-util-7.0.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\net\fabricmc\yarn\1.14+build.1\yarn-1.14+build.1.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\me\deftware\subsystem\latest-separate\subsystem-latest-separate.jar
[info] Found library: C:\Users\mason\AppData\Roaming\.minecraft\libraries\me\deftware\EMC-F\latest-1.14\EMC-F-latest-1.14.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-10,1,main]
[crash] java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:142)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:134)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:129)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:33)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:100)
	at amidst.threading.WorkerExecutor.lambda$run$13(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more

**Comment by moulins** [comment]
It seems you are using a modded profile, which isn't supported by Amidst.
Please try again with a vanilla profile ;)

**Comment by moulins** [comment]
No response in 6 months; closing this issue.
