### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by sjackser** [toolbox4minecraft/amidst#496]
[info] Amidst v4.2
[info] Current system time: 2019-05-23 16:00:01.526
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_201'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'D:\Minecraft\.minecraft', libraries: 'D:\Minecraft\.minecraft\libraries'
[info] using minecraft version directory. versionId: 'unknown', jar file: 'D:\Minecraft\.minecraft\versions\1.14.1\1.14.1.jar', json file: 'D:\Minecraft\.minecraft\versions\1.14.1\1.14.1.json'
[info] Loading libraries.
[info] Found library: D:\Minecraft\.minecraft\libraries\com\mojang\patchy\1.1\patchy-1.1.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\com\mojang\javabridge\1.0.22\javabridge-1.0.22.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\com\mojang\brigadier\1.0.17\brigadier-1.0.17.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\com\mojang\datafixerupper\2.0.24\datafixerupper-2.0.24.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\com\mojang\realms\1.14.15\realms-1.14.15.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl\3.2.1\lwjgl-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.2.1\lwjgl-jemalloc-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.2.1\lwjgl-openal-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.2.1\lwjgl-opengl-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.2.1\lwjgl-glfw-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.2.1\lwjgl-stb-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl\3.2.1\lwjgl-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.2.1\lwjgl-jemalloc-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.2.1\lwjgl-openal-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.2.1\lwjgl-opengl-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.2.1\lwjgl-glfw-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.2.1\lwjgl-stb-3.2.1-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3-natives-windows.jar
[info] Found library: D:\Minecraft\.minecraft\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3-natives-windows.jar
[info] Skipping library: ca.weblite:java-objc-bridge:1.0.0
[info] Skipping library: ca.weblite:java-objc-bridge:1.0.0
[info] Unable to recognise Minecraft Version with the magic string "bhmcofahkagdvxqcxq[Jxmwtwrcebekzdrgrjcotrdrezl".
[info] Reading 1.14.1.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceCreationException: unable to create local minecraft interface
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:50)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:99)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:71)
	at amidst.mojangapi.MojangApiBuilder.construct(MojangApiBuilder.java:41)
	at amidst.Application.createMojangApi(Application.java:54)
	at amidst.Application.<init>(Application.java:42)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$60(Amidst.java:162)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: amidst.clazz.real.JarFileParsingException: Error extracting jar data.
	at amidst.clazz.real.RealClasses.readRealClassesFromJarFile(RealClasses.java:37)
	at amidst.clazz.real.RealClasses.fromJarFile(RealClasses.java:23)
	at amidst.clazz.Classes.createSymbolicClassMap(Classes.java:35)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:35)
	... 21 more
Caused by: amidst.clazz.real.RealClassCreationException: unable to create real class for the class: dhj
	at amidst.clazz.real.RealClassBuilder.construct(RealClassBuilder.java:18)
	at amidst.clazz.real.RealClasses.readRealClass(RealClasses.java:72)
	at amidst.clazz.real.RealClasses.readJarFileEntry(RealClasses.java:58)
	at amidst.clazz.real.RealClasses.readJarFile(RealClasses.java:45)
	at amidst.clazz.real.RealClasses.readRealClassesFromJarFile(RealClasses.java:33)
	... 24 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(Unknown Source)
	at amidst.clazz.real.RealClassBuilder.skipAttributes(RealClassBuilder.java:265)
	at amidst.clazz.real.RealClassBuilder.readFields(RealClassBuilder.java:227)
	at amidst.clazz.real.RealClassBuilder.doConstruct(RealClassBuilder.java:47)
	at amidst.clazz.real.RealClassBuilder.construct(RealClassBuilder.java:16)
	... 28 more

**Comment by moulins** [comment]
You need to use the latest version of Amidst ([here](https://github.com/toolbox4minecraft/amidst/releases)) to open Minecraft 1.14 profiles.
