### ISSUE TITLE
amidst gives me this when I run it 

### ISSUE THREAD

**Issue by Piggerts** [toolbox4minecraft/amidst#519]
[info] Amidst v4.3
[info] Current system time: 2019-07-25 15:53:13.523
[info] System.getProperty("os.name") == 'Windows 7'
[info] System.getProperty("os.version") == '6.1'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_221'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: default
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.NullPointerException
	at java.io.File.<init>(Unknown Source)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.getMinecraftDirectory(DotMinecraftDirectoryService.java:81)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.findDotMinecraftDirectory(DotMinecraftDirectoryService.java:73)
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createDotMinecraftDirectory(DotMinecraftDirectoryService.java:46)
	at amidst.mojangapi.file.MinecraftInstallation.newLocalMinecraftInstallation(MinecraftInstallation.java:41)
	at amidst.PerApplicationInjector.<init>(PerApplicationInjector.java:66)
	at amidst.Amidst.doStartApplication(Amidst.java:171)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:162)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by burgerguy** [comment]
For amidst to work you need to have minecraft installed and a profile in the minecraft launcher has to have been run at least once.
