### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by Silversai** [toolbox4minecraft/amidst#706]
[info] Amidst v4.3
[info] Current system time: 2020-03-03 18:33:41.557
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'x86'
[info] System.getProperty("java.version") == '1.8.0_231'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '32'
[info] Not using OpenGL.
[info] Biome profile activated: default
[info] using '.minecraft' directory at: 'C:\Users\zombi\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'Latest version'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:154)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'Latest snapshot'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:154)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[warning] unable to check for updates
[warning] java.net.UnknownHostException: toolbox4minecraft.github.io
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at amidst.parsing.URIUtils.newInputStream(URIUtils.java:45)
	at amidst.parsing.URIUtils.newReader(URIUtils.java:37)
	at amidst.parsing.URIUtils.newReader(URIUtils.java:33)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:35)
	at amidst.gui.main.UpdateInformationRetriever.retrieve(UpdateInformationRetriever.java:18)
	at amidst.threading.WorkerExecutor.lambda$run$15(WorkerExecutor.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[warning] Error while downloading remote version list.
[warning] java.net.UnknownHostException: launchermeta.mojang.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at amidst.parsing.URIUtils.newInputStream(URIUtils.java:45)
	at amidst.parsing.URIUtils.newReader(URIUtils.java:37)
	at amidst.parsing.URIUtils.newReader(URIUtils.java:33)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:35)
	at amidst.mojangapi.file.service.VersionListService.readRemoteVersionList(VersionListService.java:21)
	at amidst.mojangapi.file.VersionList.newRemoteVersionList(VersionList.java:16)
	at amidst.mojangapi.file.VersionListProvider.doDownload(VersionListProvider.java:55)
	at amidst.threading.WorkerExecutor.lambda$run$15(WorkerExecutor.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[info] using minecraft launcher profile '' with versionId '1.15.1'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library com.mojang:javabridge:1.0.22 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.17 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
[info] Found library com.mojang:datafixerupper:2.0.24 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.5.25 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.1
[info] Found library org.lwjgl:lwjgl:3.2.2 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.1
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.2 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.1
[info] Found library org.lwjgl:lwjgl-openal:3.2.2 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.1
[info] Found library org.lwjgl:lwjgl-opengl:3.2.2 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.1
[info] Found library org.lwjgl:lwjgl-glfw:3.2.2 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.1
[info] Found library org.lwjgl:lwjgl-stb:3.2.2 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.1
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.2 at file:/C:/Users/zombi/AppData/Roaming/.minecraft/libraries/org/lwjgl

**Comment by moulins** [comment]
Please use the latest version of Amidst ([v4.4](https://github.com/toolbox4minecraft/amidst/releases/tag/v4.4)).
