### ISSUE TITLE
Amidst crashed!

### ISSUE THREAD

**Issue by ic22487** [toolbox4minecraft/amidst#707]
[info] Amidst v4.4
[info] Current system time: 2020-03-04 13:17:03.329
[info] System.getProperty("os.name") == 'Mac OS X'
[info] System.getProperty("os.version") == '10.13.6'
[info] System.getProperty("os.arch") == 'x86_64'
[info] System.getProperty("java.version") == '1.8.0_181'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Enabling OpenGL.
[info] Biome profile activated: default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: '/Users/iancarter/Library/Application Support/minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[info] Scanning for profiles.
[info] There are no updates available.
[info] Successfully loaded remote version list.
[info] Successfully loaded profile list.
[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'Baritone'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:153)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'Heck'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:153)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'Combat Test'
	at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:153)
	at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:51)
	at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:62)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[info] using minecraft launcher profile 'Latest version' with versionId '1.15.2'
[info] Loading libraries.
[info] Found library com.mojang:patchy:1.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
[info] Found library oshi-project:oshi-core:1.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
[info] Found library net.java.dev.jna:jna:4.4.0 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
[info] Found library net.java.dev.jna:platform:3.4.0 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
[info] Found library com.ibm.icu:icu4j-core-mojang:51.2 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
[info] Found library com.mojang:javabridge:1.0.22 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
[info] Found library net.sf.jopt-simple:jopt-simple:5.0.3 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
[info] Found library io.netty:netty-all:4.1.25.Final at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
[info] Found library com.google.guava:guava:21.0 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
[info] Found library org.apache.commons:commons-lang3:3.5 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
[info] Found library commons-io:commons-io:2.5 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
[info] Found library commons-codec:commons-codec:1.10 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
[info] Found library net.java.jinput:jinput:2.0.5 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
[info] Found library net.java.jutils:jutils:1.0.0 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
[info] Found library com.mojang:brigadier:1.0.17 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
[info] Found library com.mojang:datafixerupper:2.0.24 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
[info] Found library com.google.code.gson:gson:2.8.0 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
[info] Found library com.mojang:authlib:1.5.25 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
[info] Found library org.apache.commons:commons-compress:1.8.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[info] Found library org.apache.httpcomponents:httpclient:4.3.3 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
[info] Found library commons-logging:commons-logging:1.1.3 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[info] Found library org.apache.httpcomponents:httpcore:4.3.2 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
[info] Found library it.unimi.dsi:fastutil:8.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
[info] Found library org.apache.logging.log4j:log4j-api:2.8.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[info] Found library org.apache.logging.log4j:log4j-core:2.8.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[info] Found library org.lwjgl:lwjgl:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.2
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.2
[info] Found library org.lwjgl:lwjgl-openal:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.2
[info] Found library org.lwjgl:lwjgl-opengl:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.2
[info] Found library org.lwjgl:lwjgl-glfw:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.2
[info] Found library org.lwjgl:lwjgl-stb:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.2
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.2
[info] Found library org.lwjgl:lwjgl:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl:3.2.2
[info] Found library org.lwjgl:lwjgl-jemalloc:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-jemalloc:3.2.2
[info] Found library org.lwjgl:lwjgl-openal:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-openal:3.2.2
[info] Found library org.lwjgl:lwjgl-opengl:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-opengl:3.2.2
[info] Found library org.lwjgl:lwjgl-glfw:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-glfw:3.2.2
[info] Found library org.lwjgl:lwjgl-stb:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-tinyfd:3.2.2
[info] Found library org.lwjgl:lwjgl-tinyfd:3.2.1 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1-natives-macos.jar
[info] Skipping inactive library org.lwjgl:lwjgl-stb:3.2.2
[info] Found library com.mojang:text2speech:1.11.3 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
[info] Found library com.mojang:text2speech:1.11.3 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
[info] Found library ca.weblite:java-objc-bridge:1.0.0 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar
[info] Found library ca.weblite:java-objc-bridge:1.0.0 at file:/Users/iancarter/Library/Application%20Support/minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar
[info] Finished loading libraries.
[info] Recognised Minecraft Version 1.15.2 with the magic string "bkacrpajsaikxurwzo[Jzkyqyocrbgxabbtacrjtdcsccsbsxsyabj".
[info] Reading 1.15.2.jar
[info] Jar load complete.
[info] Searching for classes...
[info] Found class Biome: bkt
[info] Found class WorldData: crm
[info] Found class RegistryKey: sm
[info] Found class Registry: gb
[info] Found class NoiseBiomeProvider: bkv$a
[info] Found class WorldSettings: bka
[info] Found class OverworldBiomeZoomer: bmb
[info] Found class WorldType: bkd
[info] Found class GameType: bjt
[info] Class search complete.
[info] Loading classes...
[info] Classes loaded.
[info] Minecraft load complete.
[info] Not writing to seed history file, because it does not exist: history.txt
[info] Creating world with seed '-2143500864' and type 'Default'
[info] Using the following generator options: 
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.ExceptionInInitializerError
	at ace.a(SourceFile:314)
	at ace.b(SourceFile:170)
	at ace.<clinit>(SourceFile:166)
	at aku$a.a(SourceFile:664)
	at aku.a(SourceFile:141)
	at aku.<clinit>(SourceFile:147)
	at beo.<clinit>(SourceFile:611)
	at cvv.<clinit>(SourceFile:12)
	at cvq.a(SourceFile:9)
	at byj.h(SourceFile:204)
	at bph.b(SourceFile:539)
	at byj$a.<init>(SourceFile:420)
	at byj$a.<init>(SourceFile:404)
	at byj.c(SourceFile:70)
	at bpi.<clinit>(SourceFile:720)
	at gb.N(SourceFile:81)
	at gb.a(SourceFile:125)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
	at gb.<clinit>(SourceFile:124)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at amidst.clazz.symbolic.SymbolicField.get(SymbolicField.java:45)
	at amidst.clazz.symbolic.SymbolicField.getValueFromObject(SymbolicField.java:36)
	at amidst.clazz.symbolic.SymbolicField.getStaticValue(SymbolicField.java:32)
	at amidst.clazz.symbolic.SymbolicClass.getStaticFieldValue(SymbolicClass.java:103)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.initializeIfNeeded(LocalMinecraftInterface.java:196)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterface.createWorld(LocalMinecraftInterface.java:125)
	at amidst.mojangapi.minecraftinterface.LoggingMinecraftInterface.createWorld(LoggingMinecraftInterface.java:26)
	at amidst.mojangapi.world.WorldBuilder.create(WorldBuilder.java:122)
	at amidst.mojangapi.world.WorldBuilder.from(WorldBuilder.java:67)
	at amidst.mojangapi.RunningLauncherProfile.createWorld(RunningLauncherProfile.java:77)
	at amidst.gui.main.WorldSwitcher.displayWorld(WorldSwitcher.java:67)
	at amidst.gui.main.Actions.newFromSeed(Actions.java:77)
	at amidst.gui.main.Actions.newFromSeed(Actions.java:64)
	at amidst.gui.main.menu.Menus.lambda$item$2(Menus.java:138)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.SecurityException: SHA-256 digest error for acy.class
	at sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:223)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:243)
	at java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:484)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at add.<clinit>(SourceFile:48)
	... 77 more

**Comment by moulins** [comment]
Are you using a modded Minecraft profile? If it is the case, Amidst won't work, as it requires a vanilla profile.

**Comment by ic22487** [comment]
i was using a normal minecraft profile, but there was a modded one available in the launcher.

**Comment by ic22487** [comment]
The mods that were available werent something that would edit the terrain generation either

**Comment by moulins** [comment]
> The mods that were available werent something that would edit the terrain generation either

Any modification to the Minecraft JAR, even if it doesn't affect terrain generation, has the potential to break Amidst.

Your error (`java.lang.SecurityException: SHA-256 digest error for acy.class`) seems to indicate that the Minecraft JAR is somehow corrupted; maybe try to delete it and redownload it again?
