### ISSUE TITLE
Optifine profile causes Amidst4.0 to crash

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#71]
As far as I know Optifine doesn't have an effect upon world generation.
Why does Amidst crash when pointed at an Optifine profile?
Can this be fixed easily?

Not that this is really critical since the Optifine installer leaves the original profile alone and unmodified but since the Optifine profiles show up on the profile selection menu some users are going to be constantly shooting themselves in the foot.

**Comment by stefandollase** [comment]
Can you post the crash report? In general, you know [the statement about modded profiles](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#can-i-use-amidst-with-a-modded-minecraft-version). If the mod does not alter biome generation it might just work, but it might as well not work.

If the jar file is modded, classes are modified. If one of the modified classes happens to be one of the classes used by Amidst, Amidst cannot work with this jar file. It seems like Optifine does indeed change one of the used classes, so that would be the reason why it does not work.

**Comment by BigAlanM** [comment]
Here's the crash report:
Conditions: Windows 10, Amidst4.0b8, Latest Optifine for MC1.8.9
************************************
[info] Amidst v4.0-beta8
[info] Biome color profile activated.
[info] using '.minecraft' directory at: 'C:\Users\Alan\AppData\Roaming\.minecraft', libraries: 'C:\Users\Alan\AppData\Roaming\.minecraft\libraries'
[info] using biome color profiles at: 'biome-color-profiles'
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[info] Beginning latest version list load.
[info] Attempting to download remote version list...
[info] Successfully loaded version list. URL: https://s3.amazonaws.com/Minecraft.Download/versions/versions.json
[info] using minecraft launcher profile 'OptiFine189H2' with versionId '1.8.9-OptiFine_HD_U_H2'
[info] Loading libraries.
[info] Found library: C:\Users\Alan\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.8.9_HD_U_H2\OptiFine-1.8.9_HD_U_H2.jar
[info] Found library: C:\Users\Alan\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.7\launchwrapper-1.7.jar
[crash] Amidst has encounted an uncaught exception on the thread Thread[Thread-11,1,main]
[crash] java.lang.NoClassDefFoundError: io/netty/buffer/ByteBufOutputStream
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:132)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:123)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:117)
	at amidst.mojangapi.minecraftinterface.local.LocalMinecraftInterfaceBuilder.create(LocalMinecraftInterfaceBuilder.java:34)
	at amidst.mojangapi.file.directory.VersionDirectory.createLocalMinecraftInterface(VersionDirectory.java:106)
	at amidst.mojangapi.MojangApi.set(MojangApi.java:74)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:82)
	at amidst.threading.WorkerExecutor.lambda$run$11(WorkerExecutor.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: io.netty.buffer.ByteBufOutputStream
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more

**Comment by stefandollase** [comment]
The crash is indeed caused by how Optifine modifies the profile files. Thus, this I will mark this bug as invalid, because Amidst does not support modded versions.

**Comment by stefandollase** [comment]
see #110
