### ISSUE TITLE
Posting this here cause it's the only for AMIDST to allow me to use the program 😒

### ISSUE THREAD

**Issue by ComparatorClock** [toolbox4minecraft/amidst#736]
[crash] Amidst has encounted an uncaught exception on the thread Thread[main,5,main]
[crash] java.lang.IllegalArgumentException: unable to load resource: '/amidst/icon/amidst-16x16.png'
	at amidst.ResourceLoader.getImage(ResourceLoader.java:38)
	at amidst.Amidst.createMetadata(Amidst.java:62)
	at amidst.Amidst.parseCommandLineArgumentsAndRun(Amidst.java:44)
	at amidst.Amidst.main(Amidst.java:30)
Caused by: javax.imageio.IIOException: Can't create cache file!
	at javax.imageio.ImageIO.createImageInputStream(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)
	at amidst.ResourceLoader.getImage(ResourceLoader.java:34)
	... 3 more
Caused by: java.nio.file.NoSuchFileException: C:\Users\John\AppData\Local\Temp\imageio9116425300589211553.tmp
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
	at java.nio.file.Files.newByteChannel(Unknown Source)
	at java.nio.file.Files.createFile(Unknown Source)
	at java.nio.file.TempFileHelper.create(Unknown Source)
	at java.nio.file.TempFileHelper.createTempFile(Unknown Source)
	at java.nio.file.Files.createTempFile(Unknown Source)
	at javax.imageio.stream.FileCacheImageInputStream.<init>(Unknown Source)
	at com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(Unknown Source)
	... 6 more

**Comment by moulins** [comment]
Can't reproduce the crash on my machine. Did you save the Amidst.exe in a suitable location before launching it?

**Comment by ComparatorClock** [comment]
... What counts as a suitable location? I had it sit in my downloads
folder, and it was working fine before.

**Comment by moulins** [comment]
The `C:\Users\John\AppData\Local\Temp\imageio9116425300589211553.tmp` path is very suspiscious, and made me think you've downloaded a zip file and launched the program without decompressing the zip. This won't work, because Amidst needs to access the JAR file to load its resources.
