### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by Twulkis** [toolbox4minecraft/amidst#743]
When I try to open amdst this window show up ı tried ctrl+O but nothing happens
I think amdst cant locate minecraft files. is there a way to fix? (I am currently using manjaro linux)
![Screenshot_20200424_010741](https://user-images.githubusercontent.com/40734053/80154872-1aa28280-85c9-11ea-9180-6ad1def1b3a2.png)

**Comment by moulins** [comment]
Is your Minecraft installation in a custom location? Amidst will search Minecraft files in `~/.minecraft` by default.

You can either make a symlink here pointing to the actual `.minecraft` folder, or use the [command line interface](https://github.com/toolbox4minecraft/amidst/wiki/Command-Line-Interface) to specify the correct location with the `-mcpath` argument.

**Comment by dector** [comment]
@Twulkis I guess your `launcher_profiles.json` has no active profiles.
```
$ cat ~/.minecraft/launcher_profiles.json`
```

I think it happens with non-official launchers and has nothing to do with Linux. :)

**Comment by qrrk** [comment]
Similar problem here:

![image](https://user-images.githubusercontent.com/19731636/137600675-39272636-ff47-4f83-b5a8-29566d04da41.png)

In my case it successfully finds the Minecraft directory:
`[info] using '.minecraft' directory at: '/home/user/.minecraft'`

But then this happens:
<details>

```
[info] Scanning for profiles.
[info] Successfully loaded profile list.
[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'Latest version'
        at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:154)
        at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:59)
        at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:97)
        at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

[warning] java.io.FileNotFoundException: cannot find valid version directory for launcher profile 'Latest snapshot'
        at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createValidVersionDirectory(DotMinecraftDirectoryService.java:154)
        at amidst.mojangapi.file.UnresolvedLauncherProfile.resolveToVanilla(UnresolvedLauncherProfile.java:59)
        at amidst.gui.profileselect.LocalProfileComponent.tryResolve(LocalProfileComponent.java:97)
        at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>
