### ISSUE TITLE
Amidst crash

### ISSUE THREAD

**Issue by Atomic-Typh00n** [toolbox4minecraft/amidst#764]
Crash Report:
[crash] Amidst has encounted an uncaught exception on the thread Thread[main,5,main]
[crash] java.lang.ExceptionInInitializerError
	at sun.nio.fs.WindowsFileSystem.<init>(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.<init>(Unknown Source)
	at sun.nio.fs.DefaultFileSystemProvider.create(Unknown Source)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(Unknown Source)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(Unknown Source)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(Unknown Source)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(Unknown Source)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(Unknown Source)
	at java.nio.file.FileSystems.getDefault(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at java.nio.file.TempFileHelper.<clinit>(Unknown Source)
	at java.nio.file.Files.createTempFile(Unknown Source)
	at javax.imageio.stream.FileCacheImageInputStream.<init>(Unknown Source)
	at com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(Unknown Source)
	at javax.imageio.ImageIO.createImageInputStream(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)
	at amidst.ResourceLoader.getImage(ResourceLoader.java:34)
	at amidst.Amidst.createMetadata(Amidst.java:62)
	at amidst.Amidst.parseCommandLineArgumentsAndRun(Amidst.java:44)
	at amidst.Amidst.main(Amidst.java:30)
Caused by: java.nio.charset.UnsupportedCharsetException: MS932
	at java.nio.charset.Charset.forName(Unknown Source)
	at sun.nio.fs.Util.<clinit>(Unknown Source)
	... 22 more

I uninstalled and reinstalled it, it still crashed.

**Comment by James103** [comment]
Are you trying to use Amidst with Minecraft 1.16? If so, it is currently unsupported, but may be supported in a future release (once Minecraft 1.16 comes out).

**Comment by moulins** [comment]
This doesn't look like a Minecraft 1.16 compatibility issue. Could you post the full Amidst logs?

**Comment by yllekz** [comment]
Having the same problem. Might be the Nether update.
