### ISSUE TITLE
I was told to send this to this address, so here I am.

### ISSUE THREAD

**Issue by HaviBunny** [toolbox4minecraft/amidst#766]
After I attempted to look at a map of the end, I received an error. I brushed by it and tried to reload after it crashed, but I believe I received the same message and was not allowed in once again. Here is that message:
[crash] Amidst has encounted an uncaught exception on the thread Thread[main,5,main]
[crash] java.lang.IllegalArgumentException: unable to load resource: '/amidst/icon/amidst-16x16.png'
	at amidst.ResourceLoader.getImage(ResourceLoader.java:38)
	at amidst.Amidst.createMetadata(Amidst.java:62)
	at amidst.Amidst.parseCommandLineArgumentsAndRun(Amidst.java:44)
	at amidst.Amidst.main(Amidst.java:30)
Caused by: javax.imageio.IIOException: Can't create cache file!
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:361)
	at javax.imageio.ImageIO.read(ImageIO.java:1397)
	at amidst.ResourceLoader.getImage(ResourceLoader.java:34)
	... 3 more
Caused by: java.nio.file.FileSystemException: /var/folders/vs/zf4z9y4j6qv1n16gpvzz1hq40000gn/T/imageio6846682277098340836.tmp: No space left on device
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:897)
	at javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:102)
	at com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(InputStreamImageInputStreamSpi.java:69)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
	... 5 more

**Comment by HaviBunny** [comment]
By the way, this was on the newest version of Amidst, that I'd downloaded earlier today.

**Comment by HaviBunny** [comment]
I'm not sure if this also helps at all, but I'm trying to use this on a 2020 MacBook Pro that is currently about 2-3 months old.

**Comment by HaviBunny** [comment]
One more thing; it is no longer opening to Amidst and only to that error screen.
