### ISSUE TITLE
Unable to create local minecraft interface

### ISSUE THREAD

**Issue by katalia369** [toolbox4minecraft/amidst#788]
I built a custom system for the office that runs a dual boot Windows 10 and Linux Mint 19.3 Cinnamon. I work as much as I can in Linux but most accounting software is not Linux friendly at this point. On the Linux portion of my drive, I have a working Linux 1.16.1 that loads successfully. I have installed Java 8 to Linux as well and Amidst v4.4 jar file. Initially, both Minecraft and Amidst start well, Amidst detects the 1.16.1 snapshot and version. When I click on one however I get an error I don't quite understand: 'Unable to create interface'.

I have attached a screenshot of the error. I would appreciate any directions to resolve this. I'm not great at independently developing code, but I know enough to follow it once it's presented to me. 

Thank You
Mrs. J

![Screenshot from 2020-06-28 23-55-46](https://user-images.githubusercontent.com/67572924/85975458-bbcd0100-b99d-11ea-8796-f410de215615.png)

**Comment by moulins** [comment]
Please use the latest release (v4.5-beta1) to have Minecraft 1.16 support.

(There is a bug in Amidst v4.5-beta1 preventing you from opening a world save, but it will be soon fixed in the next release)

**Comment by katalia369** [comment]
Per your advice I installed the beta 
I copied the new errors from the log
I really don't know what to make of this, i don't have enough background in java to understand.
Mrs J

[warning] java.io.IOException: [JNBT] Invalid tag type: 12.
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:208)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:191)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:191)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTagPayload(NBTInputStream.java:191)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:122)
	at org.jnbt.NBTInputStream.readTag(NBTInputStream.java:96)
	at amidst.mojangapi.file.nbt.NBTUtils.readTagFromFile(NBTUtils.java:22)
	at amidst.mojangapi.file.nbt.LevelDatNbt.from(LevelDatNbt.java:17)
	at amidst.mojangapi.file.service.SaveDirectoryService.readLevelDat(SaveDirectoryService.java:71)
	at amidst.mojangapi.file.MinecraftInstallation.newSaveGame(MinecraftInstallation.java:95)
	at amidst.gui.main.WorldSwitcher.displayWorld(WorldSwitcher.java:78)
	at amidst.gui.main.Actions.openSaveGame(Actions.java:107)
	at amidst.gui.main.menu.Menus.lambda$item$2(Menus.java:138)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6631)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6396)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5007)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
