### ISSUE TITLE
amidst 4.5 beta crash

### ISSUE THREAD

**Issue by PenguinMan32** [toolbox4minecraft/amidst#802]
opened amidst and it crashed along with crashing minecraft and freezing up my discord and chrome.

[info] Amidst v4.5-beta1
[info] Current system time: 2020-07-02 15:57:17.542
[info] System.getProperty("os.name") == 'Windows 10'
[info] System.getProperty("os.version") == '10.0'
[info] System.getProperty("os.arch") == 'amd64'
[info] System.getProperty("java.version") == '1.8.0_241'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Not using OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: 'C:\Users\Ghayth Hammad\AppData\Roaming\.minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.OutOfMemoryError: Metaspace
	at sun.font.Font2D.getStrike(Unknown Source)
	at sun.font.FontDesignMetrics.initMatrixAndMetrics(Unknown Source)
	at sun.font.FontDesignMetrics.<init>(Unknown Source)
	at sun.font.FontDesignMetrics.getMetrics(Unknown Source)
	at sun.swing.SwingUtilities2.getFontMetrics(Unknown Source)
	at javax.swing.JComponent.getFontMetrics(Unknown Source)
	at javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(Unknown Source)
	at javax.swing.plaf.basic.BasicLabelUI.getMaximumSize(Unknown Source)
	at javax.swing.JComponent.getMaximumSize(Unknown Source)
	at net.miginfocom.swing.SwingComponentWrapper.getLayoutHashCode(Unknown Source)
	at net.miginfocom.swing.MigLayout.checkCache(Unknown Source)
	at net.miginfocom.swing.MigLayout.getSizeImpl(Unknown Source)
	at net.miginfocom.swing.MigLayout.preferredLayoutSize(Unknown Source)
	at java.awt.Container.preferredSize(Unknown Source)
	at java.awt.Container.getPreferredSize(Unknown Source)
	at javax.swing.JComponent.getPreferredSize(Unknown Source)
	at javax.swing.JRootPane$RootLayout.preferredLayoutSize(Unknown Source)
	at java.awt.Container.preferredSize(Unknown Source)
	at java.awt.Container.getPreferredSize(Unknown Source)
	at javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.awt.BorderLayout.preferredLayoutSize(Unknown Source)
	at java.awt.Container.preferredSize(Unknown Source)
	at java.awt.Container.getPreferredSize(Unknown Source)
	at java.awt.Window.pack(Unknown Source)
	at amidst.gui.profileselect.ProfileSelectWindow.createFrame(ProfileSelectWindow.java:76)
	at amidst.gui.profileselect.ProfileSelectWindow.<init>(ProfileSelectWindow.java:65)
	at amidst.PerApplicationInjector.createProfileSelectWindow(PerApplicationInjector.java:114)
	at amidst.PerApplicationInjector$$Lambda$36/82690928.create(Unknown Source)
	at amidst.Application.displayProfileSelectWindow(Application.java:83)
	at amidst.Application.run(Application.java:59)
	at amidst.Amidst.doStartApplication(Amidst.java:179)
	at amidst.Amidst.lambda$startApplication$0(Amidst.java:169)

[crash] Amidst has encounted an uncaught exception on the thread Thread[AWT-EventQueue-0,6,main]
[crash] java.lang.OutOfMemoryError: (class: net/miginfocom/layout/Grid, method: <init> signature: (Lnet/miginfocom/layout/ContainerWrapper;Lnet/miginfocom/layout/LC;Lnet/miginfocom/layout/AC;Lnet/miginfocom/layout/AC;Ljava/util/Map;Ljava/util/ArrayList;)V) 
	at net.miginfocom.swing.MigLayout.checkCache(Unknown Source)
	at net.miginfocom.swing.MigLayout.layoutContainer(Unknown Source)
	at java.awt.Container.layout(Unknown Source)
	at java.awt.Container.doLayout(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validateTree(Unknown Source)
	at java.awt.Container.validate(Unknown Source)
	at java.awt.Container.validateUnconditionally(Unknown Source)
	at java.awt.Window.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at amidst.gui.crash.CrashWindow.set(CrashWindow.java:114)
	at amidst.gui.crash.CrashWindow.lambda$showAfterCrash$2(CrashWindow.java:34)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by burgerguy** [comment]
This crash happened because you ran out of ram. Either don't keep as much stuff open at once or put more ram into your computer.
