### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by dphenderson** [toolbox4minecraft/amidst#854]
Amidst crashes on launch. I can access the profile selector as long as I do not dismiss the crash log. 

Crash Log:
[info] Amidst v4.5-beta3
[info] Current system time: 2020-08-16 15:49:31.083
[info] System.getProperty("os.name") == 'Mac OS X'
[info] System.getProperty("os.version") == '10.11.6'
[info] System.getProperty("os.arch") == 'x86_64'
[info] System.getProperty("java.version") == '1.8.0_261'
[info] System.getProperty("java.vendor") == 'Oracle Corporation'
[info] System.getProperty("sun.arch.data.model") == '64'
[info] Enabling OpenGL.
[info] Biome profile activated: Default
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel
[info] using '.minecraft' directory at: '/Users/me/Library/Application Support/minecraft'
[info] using biome profiles at: 'biome'
[info] Starting to download remote version list.
[crash] Amidst has encounted an uncaught exception on the thread Thread[WorkerExecutor-0,1,main]
[crash] Amidst has encounted an uncaught exception on the thread Thread[WorkerExecutor-1,1,main]
[crash] java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.security.Provider$Service.getImplClass(Provider.java:1701)
	at java.security.Provider$Service.newInstance(Provider.java:1659)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:99)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:1001)
	at java.net.URL.openStream(URL.java:1067)
	at amidst.parsing.URIUtils.newReader(URIUtils.java:39)
	at amidst.parsing.URIUtils.newReader(URIUtils.java:35)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:36)
	at amidst.gui.main.UpdateInformationRetriever.retrieve(UpdateInformationRetriever.java:18)
	at amidst.threading.WorkerExecutor.lambda$run$15(WorkerExecutor.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[crash] java.lang.ExceptionInInitializerError
	at javax.crypto.Cipher.getInstance(Cipher.java:518)
	at sun.security.ssl.JsseJce.getCipher(JsseJce.java:189)
	at sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:483)
	at sun.security.ssl.SSLCipher.<init>(SSLCipher.java:472)
	at sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:81)
	at sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:67)
	at sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:345)
	at sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:46)
	at sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:577)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.security.Provider$Service.getImplClass(Provider.java:1701)
	at java.security.Provider$Service.newInstance(Provider.java:1659)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:99)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:1001)
	at java.net.URL.openStream(URL.java:1067)
	at amidst.parsing.URIUtils.newReader(URIUtils.java:39)
	at amidst.parsing.URIUtils.newReader(URIUtils.java:35)
	at amidst.parsing.json.JsonReader.readLocation(JsonReader.java:36)
	at amidst.mojangapi.file.service.VersionListService.readRemoteVersionList(VersionListService.java:21)
	at amidst.mojangapi.file.VersionList.newRemoteVersionList(VersionList.java:16)
	at amidst.mojangapi.file.VersionListProvider.doDownload(VersionListProvider.java:55)
	at amidst.threading.WorkerExecutor.lambda$run$15(WorkerExecutor.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:93)
	... 35 more
Caused by: java.lang.SecurityException: The jurisdiction policy files are not signed by the expected signer! (Policy files are specific per major JDK release.Ensure the correct version is installed.)
	at javax.crypto.JarVerifier.verifyPolicySigned(JarVerifier.java:336)
	at javax.crypto.JceSecurity.loadPolicies(JceSecurity.java:378)
	at javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:323)
	at javax.crypto.JceSecurity.access$000(JceSecurity.java:50)
	at javax.crypto.JceSecurity$1.run(JceSecurity.java:85)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:82)
	... 35 more

[info] Scanning for profiles.
[info] Successfully loaded profile list.

**Comment by moulins** [comment]
This looks like a Java misconfiguration issue; the relevant error is:
> java.lang.SecurityException: The jurisdiction policy files are not signed by the expected signer! (Policy files are specific per major JDK release.Ensure the correct version is installed.)

**Comment by dphenderson** [comment]
The issue was the JRE. The error appeared after the latest JRE update. Removed and re-installed JRE; problem solved.
