### ISSUE TITLE
invalid .minecraft directory

### ISSUE THREAD

**Issue by MrGeorgen** [toolbox4minecraft/amidst#907]
amidst complains about invalid minecraft directory although mcjar and mcjson options are specified 
```
$ java -jar amidst-v4-6.jar -mcjar ~/.local/share/multimc/libraries/com/mojang/minecraft/1.16.3/minecraft-1.16.3-client.jar -mcjson ~/.local/share/multimc/meta/net.minecraft/1.16.3.json -world-type default -seed 6108712586583442330 
[info] Amidst v4.6 
[info] Current system time: 2020-10-05 20:48:20.215 
[info] System.getProperty("os.name") == 'Linux' 
[info] System.getProperty("os.version") == '5.8.11-gentoo' 
[info] System.getProperty("os.arch") == 'amd64' 
[info] System.getProperty("java.version") == '1.8.0_265' 
[info] System.getProperty("java.vendor") == 'Oracle Corporation' 
[info] System.getProperty("sun.arch.data.model") == '64' 
[info] Not using OpenGL. 
[info] Biome profile activated: Default 
[info] Using look & feel: javax.swing.plaf.metal.MetalLookAndFeel 
[warning] amidst.mojangapi.file.DotMinecraftDirectoryNotFoundException: invalid '.minecraft' directory at: '/home/mrgeorgen/.minecraft' 
        at amidst.mojangapi.file.service.DotMinecraftDirectoryService.validate(DotMinecraftDirectoryService.java:57) 
        at amidst.mojangapi.file.service.DotMinecraftDirectoryService.createDotMinecraftDirectory(DotMinecraftDirectoryService.java:47) 
        at amidst.mojangapi.file.MinecraftInstallation.newLocalMinecraftInstallation(MinecraftInstallation.java:41) 
        at amidst.PerApplicationInjector.<init>(PerApplicationInjector.java:67) 
        at amidst.Amidst.doStartApplication(Amidst.java:173) 
        at amidst.Amidst.lambda$startApplication$0(Amidst.java:163) 
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) 
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) 
        at java.awt.EventQueue.access$500(EventQueue.java:97) 
        at java.awt.EventQueue$3.run(EventQueue.java:709) 
        at java.awt.EventQueue$3.run(EventQueue.java:703) 
        at java.security.AccessController.doPrivileged(Native Method) 
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) 
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) 
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) 
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) 
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) 
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) 
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 
New Default Acceleration Threshold: 0 
```

**Comment by moulins** [comment]
This is expected behavior: Amidst always requires a `.minecraft` directory, even when specifying `-mcjson` and `-mcjar` (you can specify a custom location with `-mcpath`).

The easiest solution is simply to create an Amidst-specific profile in the official Minecraft launcher and use that.  

If you don't want to use the official Launcher, you'll have to create a 'fake' `.minecraft` folder somewhere, with the following contents:
```shell
.minecraft/
  - libraries/ - symlink to multimc/libraries
  - saves/
  - versions/
  - launcher_profiles.json, with contents:
      {}
```
and specify `-mcpath` when launching Amidst.
