### ISSUE TITLE
Amidst-v4.6.jar crashes on launch

### ISSUE THREAD

**Issue by zisis912** [toolbox4minecraft/amidst#947]
```[crash] Amidst has encounted an uncaught exception on the thread Thread[main,5,main]
[crash] java.lang.IllegalArgumentException: unable to load resource: '/amidst/metadata.properties'
	at amidst.ResourceLoader.getProperties(ResourceLoader.java:50)
	at amidst.Amidst.createMetadata(Amidst.java:61)
	at amidst.Amidst.parseCommandLineArgumentsAndRun(Amidst.java:44)
	at amidst.Amidst.main(Amidst.java:30)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.util.Properties$LineReader.readLine(Unknown Source)
	at java.util.Properties.load0(Unknown Source)
	at java.util.Properties.load(Unknown Source)
	at amidst.ResourceLoader.getProperties(ResourceLoader.java:45)
	... 3 more```
this is the crash report. help me

**Comment by burgerguy** [comment]
Where is the jar located on your computer? If it’s in something like a zip file, it will not run correctly.

**Comment by zisis912** [comment]
it is actually in a folder, but it is inside a folder with spaces in its name. That couldn't be the issue, could it?

**Comment by zisis912** [comment]
(oh btw it actually was the issue)
