### ISSUE TITLE
"Amidst crashed!"

### ISSUE THREAD

**Issue by DADi590** [toolbox4minecraft/amidst#956]
As soon as I open AMIDST, this error comes up:
```
[crash] Amidst has encounted an uncaught exception on the thread Thread[main,5,main]
[crash] java.lang.IllegalArgumentException: unable to load resource: '/amidst/metadata.properties'
	at amidst.ResourceLoader.getProperties(ResourceLoader.java:50)
	at amidst.Amidst.createMetadata(Amidst.java:61)
	at amidst.Amidst.parseCommandLineArgumentsAndRun(Amidst.java:44)
	at amidst.Amidst.main(Amidst.java:30)
Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.util.Properties$LineReader.readLine(Unknown Source)
	at java.util.Properties.load0(Unknown Source)
	at java.util.Properties.load(Unknown Source)
	at amidst.ResourceLoader.getProperties(ResourceLoader.java:45)
	... 3 more
```
I didn't come on Minecraft since years, so for me it's not really importante that this would be fixed. Though might be for someone else, so the error is here. Hope it gets fixed! (Also I take the opportunity to thank you very much since this was really cool when I used to play - might get to it again some day, since I love Minecraft).

**Comment by burgerguy** [comment]
Where is the exe or jar stored at? If it’s in a zip or something similar, extract it first.

**Comment by DADi590** [comment]
Nope. Wasn't on any ZIP. And now because of that, found out what was the problem. Exclamation marks on the folder name. Weird it throws errors because of that. Thank you!
