### ISSUE TITLE
[crash] Amidst has encounted an uncaught exception on the thread Thread[WorkerExecutor-0,1,main]

### ISSUE THREAD

**Issue by difusao** [toolbox4minecraft/amidst#963]
[crash] Amidst has encounted an uncaught exception on the thread Thread[WorkerExecutor-0,1,main]
[crash] java.lang.SecurityException: class "aob"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.getMainClassFields(RecognisedVersion.java:269)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.generateMagicString(RecognisedVersion.java:260)
	at amidst.mojangapi.minecraftinterface.RecognisedVersion.from(RecognisedVersion.java:255)
	at amidst.mojangapi.minecraftinterface.MinecraftInterfaces.fromLocalProfile(MinecraftInterfaces.java:33)
	at amidst.mojangapi.RunningLauncherProfile.from(RunningLauncherProfile.java:26)
	at amidst.mojangapi.LauncherProfileRunner.run(LauncherProfileRunner.java:22)
	at amidst.gui.profileselect.LocalProfileComponent.tryLoad(LocalProfileComponent.java:142)
	at amidst.threading.WorkerExecutor.lambda$run$9(WorkerExecutor.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by moulins** [comment]
The latest Minecraft snapshot now requires Java 1.16, and Amidst isn't compatible with it yet (see #960).
This will be fixed in the next release.
